### ISSUE TITLE
read ETIMEDOUT after a few hours

### ISSUE THREAD

**Issue by kartast** [node-apn/node-apn#100]
Hi,

I am encountering read ETIMEDOUT error after starting for a few hours. This happens all the time, im runing on node.js 0.8.x.

Any idea whats causing this?

**Comment by matteocontrini** [comment]
This is a Node.js issue, it seems http://stackoverflow.com/questions/15011239/node-js-app-begins-timing-out-etimedout-when-http-connecting-to-other-sites-af
