### ISSUE TITLE
Only one connection to APNS and EPIPE errors

### ISSUE THREAD

**Issue by rskvazh** [node-apn/node-apn#125]
Why this lib opens only one connection to Apple's servers under heavy load? With fastMode and without.

I've tried to process.nextTick(function () { apn.pushNotification(...) }), but nothing helps.

Total sockets is always 1.

<pre>
hu, 26 Sep 2013 12:20:28 GMT apn 43162 left to send
Thu, 26 Sep 2013 12:20:28 GMT apn 43163 left to send
Thu, 26 Sep 2013 12:20:28 GMT apn 43164 left to send
Thu, 26 Sep 2013 12:20:28 GMT apn 43165 left to send
Thu, 26 Sep 2013 12:20:28 GMT apn 43166 left to send
Thu, 26 Sep 2013 12:20:28 GMT apn 43167 left to send
Thu, 26 Sep 2013 12:20:28 GMT apn Socket drained 215
[apns] transmitted to d17b1c29ca57cf7bc7a91db83ffbd0d0139b4c717fb73dcbaf47e1ef1dd41a8c
Thu, 26 Sep 2013 12:20:28 GMT apn Socket error occurred 215 { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
Thu, 26 Sep 2013 12:20:28 GMT apn Raising error: { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' } null undefined
Thu, 26 Sep 2013 12:20:28 GMT apn Error occurred with trace: Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
Thu, 26 Sep 2013 12:20:28 GMT apn Destroying connection 215
Thu, 26 Sep 2013 12:20:28 GMT apn Socket closed 215
[apns] disconnected from apns, total: 0
Thu, 26 Sep 2013 12:20:28 GMT apn 43167 left to send
Thu, 26 Sep 2013 12:20:28 GMT apn Socket error occurred 215 { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
Thu, 26 Sep 2013 12:20:28 GMT apn Raising error: { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' } null undefined
Thu, 26 Sep 2013 12:20:28 GMT apn Error occurred with trace: Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
Thu, 26 Sep 2013 12:20:28 GMT apn Destroying connection 215
Thu, 26 Sep 2013 12:20:28 GMT apn 43167 left to send
Thu, 26 Sep 2013 12:20:28 GMT apn 43168 left to send
Thu, 26 Sep 2013 12:20:28 GMT apn 43169 left to send
Thu, 26 Sep 2013 12:20:28 GMT apn 43170 left to send
</pre>

PS. Thanks for the great product!

**Comment by guytuboul** [comment]
Can i suggest a connection pool? Instead of having one connection,and then get a disconnect and then open a new connection (I notice a lot of connect,disconnect on my servers)

**Comment by argon** [comment]
The module will establish a connection pool if you specify the `maxConnections` property.

**Comment by guytuboul** [comment]
O.k thanks :+1:

**Comment by guytuboul** [comment]
I have maxConnection=15,but this code:
this.emit('connected', this.sockets.length + 1) always emit 1  (or 0)
When I  tried to list  the open network ports and the processes i found  several (10) process that talk to service on port 2195 (This is probably the Apn service).
The question is why the socket length that the library emitted is always 1 (Or 0!!! when we got some 'disconnected')

**Comment by argon** [comment]
If the socket throughput is not a bottleneck when sending notifications then node-apn will not create additional sockets because the single socket is enough to send the notifications at full speed. I have created #273 as a `minConnections` property may assist in your case.

I do not know why there are 10 open connections to 2195. I may be mistaken, but your comment suggests that there are separate processes connecting to the port. node-apn always runs within a single process so it would not show up as multiple connections.
