### ISSUE TITLE
Send to multiple devices

### ISSUE THREAD

**Issue by simar88** [node-apn/node-apn#128]
Hi @argon , i would like to know how is possibile to send push notification to multiple devices at the same time.
Can i put an array of token inside the variable token when i do this?
<b>var myDevice = new apn.Device(token);</b>
Thanks in advance!

**Comment by mitpoo** [comment]
Hello,
I am using a push sharp code for apple push notification and i want to send push to multiple devices at once. means do not want to send push using any loop. i am adding a device tokens in list. so is there any way to use APNS push for multiple devices.

**Comment by argon** [comment]
No, to send a notification to multiple devices you must send it to each device individually. What's wrong with a loop?

**Comment by mitpoo** [comment]
I have 12K devices records.. so in c# it hangs.. i did not get any response till the time out. That is why I am asking. There is a functionality to send push to multiple devices for Android. But I want same for Apple.

**Comment by mitpoo** [comment]
@argon 
Thank you for your quick reply. I am using push sharp version 4.

**Comment by argon** [comment]
I have no experience with PushSharp so I cannot offer much help. 12k notifications is very few, it should take no more than 5 seconds to send, it sounds like perhaps there is a nuance with the library that has been overlooked?

**Comment by mitpoo** [comment]
I did not get you what you are exactly saying in last line. Can you please elaborate ?

I have even worked for custom code of push. Without any push sharp library. But looping 12000 times is much time taker in Asp.net c#. 

Thank you.

**Comment by argon** [comment]
Maybe there is a problem with the library or the way you are using it. To send 12000 notifications should take less than 5 seconds. With node-apn 12000 notifications can be sent in 2 seconds so there is no reason it should be so slow in c#.

**Comment by mitpoo** [comment]
do you have any reference url to understand concept you are saying. I may possible that I did not understand properly. I will be grate if u can help for same.

Thank you

**Comment by argon** [comment]
Please see [this comment from Apple](https://developer.apple.com/library/ios/technotes/tn2265/_index.html#//apple_ref/doc/uid/DTS40010376-CH1-TNTAG44)

> If you're seeing throughput lower than 9,000 notifications per second, your server might benefit from improved error handling logic.

If you server is slower than that then there is a problem with PushSharp or your code working incorrectly.

**Comment by mitpoo** [comment]
@argon 
Nope. I am not even geeting any response for 1000 devices. I am attaching that code file. If you can help me for same by looking logic that will be grate for me.
[ApplePushLogic.txt](https://github.com/argon/node-apn/files/201449/ApplePushLogic.txt)

**Comment by mitpoo** [comment]
@argon 

I am not even getting response for 1000 devices using my custom code or by using Pushsharp code.

Thank you

**Comment by argon** [comment]
You are opening a connection for every single notification you are sending. That will take a long time to send as a connection takes about 800ms to create. You should be reusing the connection. Please make sure you read the documentation correctly as Apple make it very clear in several places that connections must be reused.

**Comment by mitpoo** [comment]
Ok.. Let me read that document and try again for same. If still get same issue then will contact you. :)

one more request if you do not mind then can i have your mail Id so i can contact you there.

Thank you.

**Comment by lakshaydulani** [comment]
hey @mitpoo same problem with my pushsharp code..did node-apn help u in this?

**Comment by mitpoo** [comment]
No.. That did not helped.. Finally shifted to one signal. This much better
then pushsharp. I must say.. Far better..

You must try it out. "onesignal.com"

Pooja Doshi
