### ISSUE TITLE
Issues with apns.Notification()

### ISSUE THREAD

**Issue by thomaslein** [node-apn/node-apn#130]
var note = new apns.Notification();
//I cant get this to work properly. It pushes the message, but callback wont trigger in client. 
note.alert = { "body" : "This is a message", "action-loc-key" : "Play"};

//This works fine and triggers the callback in client
note.alert = "This is a message"

//The issue here is that the it keeps using the app name as a sender, it wont change "messageFrom" 
note.payload = {"messageFrom": 'Me'};

Any ideas? 

Thank you in advance.

**Comment by dkjessn** [comment]
Not receiving any push notification in iPhone but it works fine in android and apns reports no errors neither when establishing a connection nor when sending messages

Please have a look at the url below 

http://stackoverflow.com/questions/32246163/apns-messages-are-delivered-but-not-received-on-ios-device

Thanks in advance
