### ISSUE TITLE
513 Error

### ISSUE THREAD

**Issue by paterson** [node-apn/node-apn#132]
Hi there.

I've cert.pem and a key.pem files in the same directory where I'm using node-apn, but I'm getting a 513 error. 

All of the code samples below are coffeescript.

```
options = {"passphrase": "password"}
apnConnection = new apn.Connection(options)

token = "token"
myDevice = new apn.Device(toHex(token))

note = new apn.Notification()
//more here

apnConnection.pushNotification(note, myDevice)
```

As I said I'm getting a 513, furthermore when I do this:

apnConnection.on "transmissionError", (errCode, notification, device) ->
    console.error "Notification caused error: " + errCode + " for device ", device, notification

It tells me that in notification, device is null, is that a related issue?

When I try 

```
options = {"passphrase": "password", "cert":"./cert.pem", "key":"./key.pem"}
```

I get the same thing.

Any ideas? It just seems to be unable to find the files. Their permissions are set to 700, but I've tried 400 before. Same issue.

Cheers, and great module.
Niall

**Comment by sagar1987** [comment]
var apn = require('apn');

var myPhone="<device token>";

var myDevice = new apn.Device(myPhone);
var note = new apn.Notification();
note.badge = 1;
note.sound = "r.mp3";

note.alert = { "body": "Your turn!", "action-loc-key": "Play", "launch-image": "" };
note.payload = { 'messageFrom': 'Holly' };

note.device = myDevice;

var callback = function (errorNum, notification) {
console.log('Error is: %s', errorNum);
console.log("Note " + notification);
}
var options = {
gateway: 'gateway.sandbox.push.apple.com', // this URL is different for Apple's Production Servers and changes when you go to production
errorCallback: callback,
cert: __dirname + '/../_certs/cert.pem',
key: __dirname + '/../_certs/key.pem',
passphrase: null,
port: 2195,
enhanced: true,
cacheLength: 100
}

var apnsConnection = new apn.Connection(options);
apnsConnection.sendNotification(note);


I am getting Error as

Debugger listening on port 5858 Error is: 513 Note [object Object] C:\Users\sagar.j\Documents\Visual Studio 2012\Projects\NodejsWebApp2\NodejsWebAp p2\node_modules\q\q.js:155 throw e; ^

Error: ENOENT: no such file or directory, open 'C:\Users\sagar.j\Documents\Visua l Studio 2012\Projects\NodejsWebApp2_certs\cert.pem' at Error (native)

Thanks in Advance..

**Comment by bradcrispin** [comment]
@sagar1987 I can't reproduce but I would suggest placing the .pem files in the same directory as the entry point (eg main.js) for your application, and then try again using `__dirname + '/cert.pem' . 

Reason being `__dirname` may not be the path you are expecting. Try `console.log(__dirname).` before you create the connection if you want to debug.

**Comment by milosjovac** [comment]
Hi, I have the same problem.

No matter where I put .pem files(same entry point as main.js, or elsewhere), I get: Error: ENOENT: no such file or directory, open 'cert.pem'

console.log(__dirname + '/conf/dev_key.pem') logs a good path.
console.log(fs.readFileSync(__dirname + '/conf/dev_key.pem')); logs  <Buffer 42 61 67 20 41 74 74 72 69 62 75 74 65 73 0a 20 20 20 20 66 72 69 65 6e 64 6c 79 4e 61 6d 65 3a 20 69 50 68 6f 6e 65 20 44 65 76 65 6c 6f 70 65 72 3a ... > so it is definitely valid

Error happens for path and Buffer as well.
