### ISSUE TITLE
Showing Error no "8" while running push notifications for iOS

### ISSUE THREAD

**Issue by mohanwd** [node-apn/node-apn#135]
I am using three devices.The following error code is repeated for three times

Error is: 8
Note  { encoding: 'utf8',
  payload:
   { messageFrom: 'Colomer',
     aps: { badge: 1, sound: 'notification-beep.wav', alert: [Object] } },
  expiry: 0,
  identifier: 0,
  priority: 10,
  retryLimit: -1,
  device: { token: <Buffer 65 18 87 34 c8 98 9c 12 b9 16 68 b0 8d 5d 7f e2 31 2c 4c 42 21 19 84 16 01 8f aa 6f 76 a6 e9
6a> },
  alert: { body: 'New offer from Colomer', 'action-loc-key': 'View' },
  badge: 1,
  sound: 'notification-beep.wav',
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: true,
  truncateAtWordEnd: false,
  urlArgs: undefined,
  'content-available': 1,
  compiledPayload: '{"messageFrom":"Colomer","aps":{"badge":1,"sound":"notification-beep.wav","alert":{"body":"New offer
 from Colomer","action-loc-key":"View"}}}' }

**Comment by Kuzmin** [comment]
For future reference if somebody else ends up here, in my case this was caused by missing root CAs. A good guide explaining this error can be found here: https://stackoverflow.com/questions/23343910/verify-errornum-20-when-connecting-to-gateway-sandbox-push-apple-com

**Comment by medoix** [comment]
@Kuzmin how did you add the CA? Just combine it into your cert file? there is no option in node-apn to include a CA cert.

**Comment by Kuzmin** [comment]
@medoix You need to install the CA as a root CA on your computer (and subsequently the server where this will be running), or download it and provide it to the `ca` option in node-apn `Connection` constructor. The `ca` option can be seen at https://github.com/argon/node-apn/blob/master/doc/connection.markdown 

Either way, you will need to follow the verified answer on StackOverflow to ensure that you download the right certificates. (There are several similarly named CA's on entrust, the correct one should be named entrust_2048_ca.cer, and you can further verify that it's the right one by following the instructions on StackOverflow)
