### ISSUE TITLE
Not receiving any push notification in iPhone but it works fine in android

### ISSUE THREAD

**Issue by mohanwd** [node-apn/node-apn#136]
There is no error too.
How do I fix this.
please help me

**Comment by dkjessn** [comment]
Not receiving any push notification in iPhone but it works fine in android and apns reports no errors neither when establishing a connection nor when sending messages

Please have a look at the url below 

http://stackoverflow.com/questions/32246163/apns-messages-are-delivered-but-not-received-on-ios-device

Thanks in advance
