### ISSUE TITLE
Sending unified emoji via apn

### ISSUE THREAD

**Issue by dgthistle** [node-apn/node-apn#15]
Hello again Argon,

Thanks for your work on the reliability issue with bobrik. Another issue came up... I'm not sure if it's an issue on the node-apn side or on the Apple gateway side. Basically, alerts with the emoji unified standard unicode are dropped. Everything on the node side seems to work normally, but the message never arrives on the phone. If I use the old emoji softbank unicode char, for example '\ue415' for a smiley face, it works fine. If I use the new unified unicode standard, which the iPhone emoji keyboard outputs, for example '\uD83D\uDE04', it fails. Given your knowledge of apn on the node side and apple side, perhaps you might have some insight. It's possible that Apple's APN service hasn't caught up with the unified standard or doesn't accept the extended character set. Thank you for any help!

Dave

**Comment by pashtika** [comment]
Could you please share java code for sending Advance Emoji or images?

**Comment by argon** [comment]
This library is for JavaScript, not Java. Please checkout https://github.com/notnoop/java-apns for a Java version.

―A
