### ISSUE TITLE
Error 513 - Possible to use combined Cert/Key PEM file?

### ISSUE THREAD

**Issue by occasl** [node-apn/node-apn#150]
I have a PHP script that works great and sends messages to my iPhone over APNS but when I try to use this module, I get Error 513.

In my PHP code I do things a little differently (see below); namely, I remove the spaces from the device token and "hex" it.  I also use a combined cert-key.pem that Apple recommends creating using openssl cli.  In node-apn, it appears you have to define the cert and the key separately so I just use the respective cert/key pem files I create from openssl.  Any ideas why this might not be working?  Node code at the bottom.

PHP code:

```
<?php

// Put your device token here (without spaces):
$deviceToken = 'mytokengoeshere';

// Put your private key's passphrase here:
$passphrase = 'secret';

// Put your alert message here:
$message = 'You have new SRC requests to approve';

$ctx = stream_context_create();
stream_context_set_option($ctx, 'ssl', 'local_cert', 'ck.pem');
stream_context_set_option($ctx, 'ssl', 'passphrase', $passphrase);

// Open a connection to the APNS server
$fp = stream_socket_client(
    'ssl://gateway.sandbox.push.apple.com:2195', $err,
    $errstr, 60, STREAM_CLIENT_CONNECT|STREAM_CLIENT_PERSISTENT, $ctx);

if (!$fp)
    exit("Failed to connect: $err $errstr" . PHP_EOL);

echo 'Connected to APNS' . PHP_EOL;

// Create the payload body
$body['aps'] = array(
    'alert' => $message,
    'sound' => 'default',
    'badge' => 1
    );

// Encode the payload as JSON
$payload = json_encode($body);

// Build the binary notification
$msg = chr(0) . pack('n', 32) . pack('H*', $deviceToken) . pack('n', strlen($payload)) . $payload;

// Send it to the server
$result = fwrite($fp, $msg, strlen($msg));

if (!$result)
    echo 'Message not delivered' . PHP_EOL;
else
    echo 'Message successfully delivered' . PHP_EOL;

// Close the connection to the server
fclose($fp);
```

Node.js code:

```
            var message = new apn.notification();

            message.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
            message.badge = count;
            message.sound = "ping.aiff";
            message.setAlertText("You have new " + system + " requests to Approve");
            message.payload = {'messageFrom': uid};

            var options = { "gateway": "gateway.sandbox.push.apple.com", "cert": __dirname + "/../resource/cert.pem", "key:": __dirname + "/../resource/key.pem", "passphrase:": "secret" };
            var service = new apn.connection(options);

            service.on('connected', function() {
                console.log("Connected");
            });

            service.on('transmitted', function(notification, device) {
                console.log("Notification transmitted to:" + device.token.toString('hex'));
            });

            service.on('transmissionError', function(errCode, notification, device) {
                console.error("Notification caused error: " + errCode + " for device ", device, notification);
            });

            service.on('timeout', function () {
                console.log("Connection Timeout");
            });

            service.on('disconnected', function() {
                console.log("Disconnected from APNS");
            });

            service.on('socketError', console.error);

            var deviceId = "fe71811122723919abc56e7f8a8d8d8s8888c8s8a8s8s881155csafe";
            var device = new apn.Device(deviceId); 
            service.pushNotification(message, device);
```

**Comment by psuhas** [comment]
Hi occasl

I am running into similar issue as you did, how did you get the ck.pem converted to key.pem and cert.pem? Can you please paste the commands here?

I have tried following but that did not work. 
openssl pkey -in foo.pem -out foo-key.pem 
openssl x509 -in foo.pem -outform DER -out foo-cert.pem

Thanks for the help,

**Comment by argon** [comment]
You probably want `openssl rsa` instead of `openssl pkey` and `-outform` should be `PEM` not `DER`

**Comment by psuhas** [comment]
I regenerated the files. The result is same.  It stays in the loop timeout/disconnect/connect
I know the combined pem and passphrase is good as it works on PHP code 

Partial log output:

 apn 0 left to send +7ms
  apn 0 left to send +0ms
  apn Socket timeout +10s 0
timeout
  apn Destroying connection +0ms 0
  apn Removing socket from pool +0ms 0
  apn Initialising connection +0ms
  apn 0 left to send +2ms
  apn Socket closed +4ms 0
  apn Removing socket from pool +0ms 0
disconnected
  apn 0 left to send +0ms
  apn Connection established +176ms
connected  1
  apn 0 left to send +104ms

Any thoughts?

**Comment by argon** [comment]
What is the problem you are having? That log output suggests everything worked correctly.

**Comment by psuhas** [comment]
The loop never finishes, I have to kill the process every time and no notification appears on the phone. Not sure how to debug. Is there any way to pass on the combined file instead of key and cert differently? 

Thx for your quick replies..

**Comment by argon** [comment]
How many notifications are you trying to send, 1 or many?

The script won't shut down by itself. You need to call `connection.shutdown()` when you are done with it.

If the certificates were broken you should be seeing other errors.

**Comment by psuhas** [comment]
I am only sending one notification to one device. I did separation with the commands mentioned above (with your suggested values). Now that I added shutdown call, the loop ended but no notification. 

Is there any way to test the separated files independently? I am suspecting that more than anything else. 

Any thoughts will be appreciated, thx,
