### ISSUE TITLE
Need an event emit when done pushing all device tokens

### ISSUE THREAD

**Issue by deepakc** [node-apn/node-apn#199]
Can you add an event emit when you are done writing all device tokens to the socket?
Currently there is no event to know that apn is done writing all the device tokens.
We cannot rely on socket 'closed' because that happens even when there is a bad token.

**Comment by pablocaselas** [comment]
Hi,

Let's say I want to ```process.exit();``` as soon as I finish sending the messages to Apple.

If I subscribe to the "completed" event and have a counter for all the messages that should be completed before exiting the app, it should work, right? 

```
apnConnection.on("completed", function() {
                    console.log("completed from APN. numMessages--->",numMessages);
                    numMessages--;
                    if (numMessages==0){
                        console.log("going to return callback");
                        apnConnection.shutdown();
                        process.exit();
                        //return cb(null);

                    }
                });
```
This is not working for me. Which event should I subscribe to?

**Comment by argon** [comment]
You should use the connection.shutdown() method. It will close the connection after everything is sent.

―A
