### ISSUE TITLE
Error 8 when sending with p12 certificate. No problem with pem.

### ISSUE THREAD

**Issue by tanis2000** [node-apn/node-apn#228]
I have an app that is working fine using PEM key and certificate. I want to use the p12 directly to avoid having to run openssl to get the PEM key and certificate out of it so I simply changed my options to this:

```
var apnOptions = {
    pfx: p12Filename,
    production: !sandbox
};

var apnConnection = new apn.Connection(apnOptions);
```

It looks like the connections are being opened and the push notifications being sent but the outcome is that it's always error 8, no matter if using a development or production certificate. The weird thing is that the PEM key and cert were created from that same P12 files (both production and development) that I'm using for this test. 
Any clue at what might be wrong?

**Comment by PrathameshTM** [comment]
So, using the p12 file and the above mentioned syntax works?
