### ISSUE TITLE
never receiving notification

### ISSUE THREAD

**Issue by tharrington** [node-apn/node-apn#236]
I am sending a test notification using product certs and the console is saying the notification transmitted properly but it never comes through:

10:33:54 web.1  | GET /api/testnotification 202 16ms - 8b
10:33:54 web.1  | Connected
10:33:54 web.1  | Notification transmitted to:c01120a9d92fbbec6b85417a9d80ae72ce525bda4186c8ca66047b91a12528e2
10:33:54 web.1  | Disconnected from APNS

var apn = require('apn');

var options = {
    gateway : 'gateway.sandbox.push.apple.com',
    key     : process.env.KEY_PEM,
    cert    : process.env.CERT_PEM
};

// Create a connection to the service using mostly default parameters.
var service = new apn.connection(options);

service.on('connected', function() {
    console.log("Connected");
});

service.on('transmitted', function(notification, device) {
    console.log("Notification transmitted to:" + device.token.toString('hex'));
});

service.on('transmissionError', function(errCode, notification, device) {
    console.error("Notification caused error: " + errCode + " for device ", device, notification);
});

service.on('timeout', function () {
    console.log("Connection Timeout");
});

service.on('disconnected', function() {
    console.log("Disconnected from APNS");
});

service.on('socketError', console.error);

exports.pushNotification = function pushSomeNotifications(tokens, message) {

```
var note = new apn.notification();
note.setAlertText(message);
note.badge = 1;

service.pushNotification(note, tokens);
```

};

My options var looks like this:

{"gateway":"gateway.sandbox.push.apple.com","key":"./app/apis/certificates/prod-key.pem","cert":"./app/apis/certificates/prod-cert.pem"}

these are the routes to the pem files, but do I need the actual file to come through instead? Wouldn't this throw an error if this was incorrect?

**Comment by chrisabrams** [comment]
I'm having the same issue; here is the config:

    {
        "connection": {
            "cert": "./certs/prod/cert.pem",
            "key": "./certs/prod/key.pem",
            "production": true,
            "passphrase": "foo000bar"
        }

I notice that `on('connected')` fires, but `on('complete')` doesnt - however, I get no errors, and the feedback says 0 devices need to be removed.

**Comment by argon** [comment]
Please try running with `DEBUG=apn` environment variable set.
