### ISSUE TITLE
Increasing number of opened sockets; leads to EMFILE errors

### ISSUE THREAD

**Issue by Mayhem93** [node-apn/node-apn#408]
* **apn** version: 1.7.7
* **nodejs** version: 0.12.7
* the apn connection instance has no special configuration (only the required auth ones).

I have a worker written in node.js which receives messages from a message queue to process them. It then sends apn notifications after processing them. Sometimes the APN token he receives is invalid (less than 5%) so apple's server disconnects me.

It seems that after a few times the worker receives a payload of messages to process (which usually leads to 300-400 notifications that need to be sent) sockets remain opened and thus potentially reaching the ulimit for opened files. The connections never close, they remain in the **ESTABLISHED** state (they are also just idling, doing nothing)

I repeat, this doesn't happen right from the start, the sockets get cleaned, but after trying a few times (3 times in my test case) sockets remain in established state.

I can increase that limit, but that's just temporary. It's just a mater of weeks till the limit will be reached again in which case the worker will be rendered useless.

Here's what **tcptrack** looks like: http://imgur.com/a/sCPjM
... and **lsof**: http://imgur.com/a/iC973

**Comment by seriousben** [comment]
We have seen this as well.

**Comment by seriousben** [comment]
CC to @argon due to the importance of this bug.

**Comment by argon** [comment]
Hopefully this should not happen with 2.0.0

**Comment by Mayhem93** [comment]
I'll update the package and let you know if it happens again.

**Comment by r0stig** [comment]
Any progress @Mayhem93 ?

**Comment by magicdawn** [comment]
- I met too many connections case
- I met `maxConnection = 10` & create only 1 `apn.Connection` instance, but sometimes, nothing happended after `connection.pushNotofication`, no events happend

Now, I use v2 version, so far so good.

**Comment by Mayhem93** [comment]
@argon @r0stig Sorry for the late reply. The issue that was causing this behavior started because of a small bug on my code. I was constantly recreating the connection (I had a pool of connections for each application), something like *delete connections[id]* then re-instantiating the connection class. This was executing very fast (unintended behavior) and because of this sometimes it would lead to too many opened sockets in the ESTABLISHED state.

After implementing the fix, everything was clear and running fine (still using the older 1.7.7 version)

**Comment by florianreinhart** [comment]
Thanks for the feedback, @Mayhem93.

I am closing this issue.
