### ISSUE TITLE
Installation requires git to be installed (version > 2)

### ISSUE THREAD

**Issue by stockulus** [node-apn/node-apn#433]
Hi,

thanks for the great Module. Works perfekt. I just have a Problem updating to version 2 in my Production environment. It runs an alpine-node docker environment, so there is no git installed. 

Thanks for help.
Christoph

**Comment by florianreinhart** [comment]
Thanks, Christoph. This should be fixed in the latest release v2.1.1. Can you confirm?

**Comment by stockulus** [comment]
Thank you! It works!
