### ISSUE TITLE
node-apn (2.x) notification.topic (bundle id) is required to send push-notification

### ISSUE THREAD

**Issue by superserg8** [node-apn/node-apn#439]
Field 'topic' (bundle id) is not required in node-apn 1.x but required in 2.x. What is it related with? APNS message format changes or internal node-apn changes?

**Comment by florianreinhart** [comment]
This is related to changes in APNs. You can now use JSON Web Tokens or one certificate for multiple apps. To specify for which application your notification is, you need to include the topic.

See table 6-2 [here](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW16) for more information on the topic.

**Comment by superserg8** [comment]
@florianreinhart Strange things, 1.x is working fine now without 'topic' field but 2.x is not working with the same certificates without 'topic' field. Are different versions of node-apn using different versions of APNS?

**Comment by florianreinhart** [comment]
Yes, node-apn 2.x uses the HTTP/2 APNs provider API. node-apn 1.x uses the old binary socket API. Check [this](https://github.com/node-apn/node-apn/blob/master/doc/whats-new.markdown) for an overview of the changes in 2.x and read the [documentation](https://github.com/node-apn/node-apn/tree/master/doc) for more details.
