### ISSUE TITLE
Base64 Decode Error when using APNS Auth Key

### ISSUE THREAD

**Issue by mikecsh** [node-apn/node-apn#440]
I have just updated node-apn and am trying to use the new auth key system. I have downloaded my auth key as a p8 file from the developer portal and put in the KeyID and TeamID. When I try and call:

var apnProvider = new apn.Provider(options);

I receive the following error:

VError: Failed to generate token: error:0906D064:PEM routines:PEM_read_bio:bad base64 decode

Am I doing something wrong here or is this a bug? Thanks!

**Comment by florianreinhart** [comment]
How does your options object look like? You can obfuscate key and team ID.

**Comment by mikecsh** [comment]
Hi @florianreinhart - it is as follows:

```javascript
var options = {
    token: {
      key: '/data/key.p8',
      keyId: '8888888888',
      teamId: '7777777777'
    },
    production: false,
  };
```

**Comment by florianreinhart** [comment]
I am unable to reproduce this. What's your environment (node version, node-apn version, OS, etc.)?

**Comment by eladnava** [comment]
I am able to use the new Provider Authentication Tokens mechanism just fine. Just tried it out and it worked flawlessly.

**Comment by vksid** [comment]
I am getting following response while using APN Auth key to send push notification. 
failed with status code 410. 
reason : 'unregistered'

I installed the app by directly running from Xcode. 
My device token is absolutely correct, I'm using the 2.1.1 version of this module with APN Auth key. It is not working.
In another node project I'm using certificates with 1.7.8 version of this module with same device token. It is working there.

**Comment by eladnava** [comment]
Are you setting the `notification.topic` to your app's bundle ID correctly?

**Comment by vksid** [comment]
@eladnava Yes, I'm setting it same as my bundle identifier of app on Xcode.

**Comment by mikecsh** [comment]
Hm then there must be something wrong with my environment. I'm using node v5.0.0, node-apn v2.1.1 on macOS 10.12 Sierra.

I believe the error is an OpenSSL error which leads me to think that there is a problem with the auth key itself. However I already tried generating a new auth key and it had the same result.

**Comment by vksid** [comment]
@mikecsh  I was able to fix the problem by deleting the App from iPhone and generating a new token on reinstallation. Maybe There's some issue with the token is already used with certificate based authentication. But I know this is a very stupid conclusion from me 😆

**Comment by florianreinhart** [comment]
@mikecsh I would try updating node to the latest version.
@vksid This issue is about the new JSON Web Token provider authentication, not about device tokens.

**Comment by mikecsh** [comment]
@florianreinhart the issue has disappeared after updating node - thanks for the shove in the right direction and sorry for not having tried this already!

@vksid thanks for you comment but as @florianreinhart mentioned, this is the JWT auth token :)

**Comment by nakulgulati** [comment]
@mikecsh after updating, which version of node did you go to? 

I am facing the same issue but for me it works on my local environment (node v4.4) but doesn't work on server (node v5.0).

**Comment by mikecsh** [comment]
Hi @nakulgulati, I upgraded to v6.7.0 and now it's working perfectly for me. I'm pretty sure the error was coming from OpenSSL but I'm not sure what changed in the stack to cause the problem somewhere between v4.4 and v6.7.0!

**Comment by nakulgulati** [comment]
@mikecsh thanks for getting back so quickly. 

I think I will try using v5.0 (same as my server)  on my local machine and then v6 to see if the problem is resolved.

**Comment by nakulgulati** [comment]
@mikecsh I can confirm that using node v5 (tested on v5.1.0) this error is encountered but using node v4.4 or v6 it seems to work fine. 

I don't know why it doesn't work node v5.0. Should we open a new issue for it?

**Comment by mikecsh** [comment]
@nakulgulati it would be good to open an issue for node v5.0 if it is still under Long Term Support, although I don't personally have time to figure out a minimal example demonstrating the problem..

**Comment by oliversalzburg** [comment]
@mikecsh Node 5 was never under LTS: https://github.com/nodejs/LTS

**Comment by Gonzalo1987** [comment]
I have the same error using node 6.9.4, there are any solution?

**Comment by fbartolom** [comment]
I am getting:
/var/www/html/php/push/apns/node_modules/apn/lib/credentials/token/prepare.js:45
      throw new VError(err, "Failed to generate token");
      ^
VError: Failed to generate token: error:0906D064:PEM routines:PEM_read_bio:bad base64 decode
even with Node 6.9.4 What to do?

**Comment by Gonzalo1987** [comment]
Check this:
https://github.com/node-apn/node-apn/issues/524

Probably you are using openssl < 1.0.2 or your PEM file contains lines of more than 64 chars.

Install openssl 1.0.2 or split your PEM certificate

Regards!

**Comment by fbartolom** [comment]
Actually now the problem is gone. Yet the new problem is how to have a php script call the node on, or install the same thing in php. I found Redis for the former and edamov/pushok for the latter but I was not able to run Redis in my php script and the latter library needs php7 which I have problems in installing.

**Comment by Gonzalo1987** [comment]
from php you can use: 
`exec("node ./app.js", $output, $return_var);`

**Comment by fbartolom** [comment]
Ok, and how do I pass the parameters? In my case the bundle id, the token, the data and so on. I am also working at trying to send the command by curl, yet I am not able to connect to the express exposed 3000 port. So this direct command, if it works would e very benefical.

**Comment by Gonzalo1987** [comment]
...
http://stackoverflow.com/questions/4351521/how-do-i-pass-command-line-arguments

moreover you can store text in files for pass messages, etc...
