### ISSUE TITLE
Any way you can also include Typescript definition?

### ISSUE THREAD

**Issue by wanjungao** [node-apn/node-apn#441]
It would help a lot.

**Comment by florianreinhart** [comment]
I don't use TypeScript myself. But I am happy to accept a PR.

**Comment by julien-c** [comment]
I use Typescript. The definition file on DefinitelyTyped is decent, but it's for the `1.x` version.

**Comment by florianreinhart** [comment]
This needs to updated in the DefinitelyTyped repo, see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11751

**Comment by julien-c** [comment]
@florianreinhart Actually, the way forward with Typescript definitions is meant to be to include the declaration file in the actual repo. (not in a single monolithic repo) and link to it via the `typings` npm package.json key. 

So a PR to include this file in the apn repo would indeed be helpful. Not many pure-JS packages do this currently though (but it's getting there).

**Comment by florianreinhart** [comment]
Thanks @julien-c for explaining this. I am reopening the issue.
