### ISSUE TITLE
 Cannot read property 'upstream' of undefined

### ISSUE THREAD

**Issue by sidsonAidson** [node-apn/node-apn#444]
i upgraded my node-apn module from 1.7 to 2.1.1 version but I get this error while i am sending a notification:
TypeError: Cannot read property 'upstream' of undefined
    at Connection._send (/home/sysadmin/projects/server-notif-prev/node_modules/http2/lib/protocol/connection.js:314:27)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback](timers.js:533:5)

But still receve notification from devices.

**Comment by oliversalzburg** [comment]
Did you change any of your code while making the upgrade?

**Comment by moussandour** [comment]
Despite changing the function which send norification.
` sendNotificationToApns() {

        let treatResponse = response => {
            for (let i in response.sent)
            {
                if(Object.prototype.hasOwnProperty.call(response.sent, i))
                {
                    let token = response.sent[i];
                    console.green(`Notification transmitted to:  '${token.device}'`);
                }
            }

            for (let i in response.failed)
            {
                if(Object.prototype.hasOwnProperty.call(response.failed, i))
                {
                    let failed = response.failed[i];

                    if(failed.error)
                    {
                        console.red(`Notification caused error for device ${failed.device} for Reason`, failed.error.Error);

                    }
                    else
                    {
                        console.red(`Notification failled :  ${failed.status}  for device ${failed.device} for Reason: '${failed.response.reason}'`);

                    }
                }

            }
        };

        let pusherList = this.toApns;
        let apn = require("apn"),
            path = require('path');

        let apnOptions = {
            token: {
                key: path.join(APP_ROOT_PATH, "/../private/common", "APNSAuthKey_XXXXXXX.p8"),
                keyId: "XXXXXXX",
                teamId: "XXXXXX"
            },
            production: PROD === true
        };

        let apnProvider = new apn.Provider(apnOptions);

        let notif = new apn.Notification();
        notif.expiry = Math.floor(Date.now() / 1000) + this.duration;

        notif.payload = this.playload;
        notif.body = this.iosBody;
        notif.setPriority(/*this.apnsPriority*/10);
        notif.topic = "com.dealerssolution.liveauction";

        if(this.ca === true)
        {
            notif.contentAvailable = true;
            notif.alert = undefined;
            notif.sound = undefined;
            notif.badge = undefined;
            apnProvider.send(notif, pusherList).then( (response) => {
                treatResponse(response);
            });

            apnProvider.shutdown();
        }
        else{
            notif.contentAvailable = false;
            notif.alert = `${this.title}\n${this.iosBody}`;
            notif.sound = this.iosAlertSound;

            console.error(pusherList);
            console.error('ok');
            apnProvider.send(notif, pusherList).then( (response) => {
                treatResponse(response);
            });

            apnProvider.shutdown();

            
        }

    }`

**Comment by sidsonAidson** [comment]
I think it was related to the "http2" module .So I updated the module from 2.0.0 version to 3.3.6 version and error has disappeared

**Comment by florianreinhart** [comment]
We actually use a custom fork of the http2 module because the official version has leaks, see https://github.com/molnarg/node-http2/pull/200

**Comment by iamyellow** [comment]
hey! i got the same error. it droves me crazy until i started to comment stuff and suddenly it worked. i had a code which modified the prototype of arrays. it's weird but as soon as i removed it (didn't need it, it was just part of legacy code) it worked as expected. hope it helps.

**Comment by simllll** [comment]
I spend almost 2 days tracking this down, we are using agenda "cronjobs" and therefore this impacted the whole process (due to the reason it crashes).

anyways: what I did was forking http2 - implementing the code changes as mentioned by @florianreinhart  and added another fix:
https://github.com/simllll/node-http2/commit/542166028c400fef935004e07ffc4924763383b9
finally it started working again and I got APN error returns .. which turned out was good, because I didn't provide a "topic". I haven't tested it, but I guess this error could be also related with the "error handling" part...? 

so my package.json has now:
"apn": "simllll/node-apn", 
which works for now

regards

**Comment by florianreinhart** [comment]
Thanks @simllll! We should update our custom fork with your changes, if your new [PR #222](https://github.com/molnarg/node-http2/pull/222) isn't merge into node-http2 any time soon.

**Comment by florianreinhart** [comment]
@simllll as there has been no response to your PR either, could you create a PR against https://github.com/node-apn/node-http2 with your changes?

**Comment by simllll** [comment]
just did

**Comment by florianreinhart** [comment]
I have just released version 2.1.2, which includes your changes.

**Comment by mblarsen** [comment]
@iamyellow thank you thank. I had extended array with flatMap (why doesn't arrays have flatMap) and that was the cause of the HTTP2 crash.
