### ISSUE TITLE
Constructor issue

### ISSUE THREAD

**Issue by EduardJS** [node-apn/node-apn#445]
I have just used `npm update apn` to 2.1.1 version and while I did the code changes ... it seems that this happens when trying to run a test push.

```javascript
TypeError: apn.Provider is not a constructor
```

Tried uninstalling then installing again, maybe some dependencies were not there. Still same thing. Am I missing something ?

**Update**, looking into the `node_modules/apn/lib` folder I can see it's not corresponding to the one in this branch.

**Update 2**. Nevermind, seems to have been a problem with my `package.json` configuration.

**Comment by gurjindersinghkhalsa** [comment]
What is the solution?

**Comment by timisenman** [comment]
@devonauts I deleted the "apn" property from my package.json file and then ran the install script "$ npm install apn --save" again, re-ran my app, and everything was fine. Didn't change anything in the code itself. Hope that helps.
