### ISSUE TITLE
[Question] What sounds can we use?

### ISSUE THREAD

**Issue by AlexKvazos** [node-apn/node-apn#447]
I don't want to have to add any sounds to my application and I want to use the ones that are default to the system, what should I use as the `sound` property of my Notification?

**Comment by oliversalzburg** [comment]
You can play the default sound. That's it.

https://developer.apple.com/reference/uikit/uilocalnotification/1616651-soundname

**Comment by florianreinhart** [comment]
Please read Apple's documentation: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html

GitHub issues should not be used for support requests.
