### ISSUE TITLE
node-apn (2.x) get 403 ExpiredProviderToken error

### ISSUE THREAD

**Issue by arthur791004** [node-apn/node-apn#450]
Hi,

I try to use  Provider Authentication Tokens, but I got this error...

I follow the connecting method you provide:
```
var options = {
    token: {
        key: "path/to/key.p8",
        keyId: "T0K3NK3Y1D",
        teamId: "T34M1D",
    },
    production: false,
};

var apnProvider = new apn.Provider(options);
```

How can I deal with it?

Thanks.

**Comment by florianreinhart** [comment]
Do you always get this error? Is your system time set correctly?

**Comment by arthur791004** [comment]
Hi,

I set system time correctly and it success, thanks.

Thanks.
