### ISSUE TITLE
At APN@2.1.1 the send promise sometimes wasn't call

### ISSUE THREAD

**Issue by casevictor** [node-apn/node-apn#451]
I'm using the latest version, just like the examples but sometime after a period of time or a number of messages sent, the promise wasn't call until I restarted de App. 

Anyone got this behavior also?

**Comment by ir-tech** [comment]
Got this as well... running a REST API on node with underlying node-apn to send notifications.

The first notification is sent properly with the promise methods called. Further notifications are not sent, until i reconnect (new instance of apn.provider)

Greetings

**Comment by casevictor** [comment]
Duplicate of #449

**Comment by casevictor** [comment]
@iliraga do you had a workaround for that? 
I tried to compare `apnConnection` with `null` but did'nt work.

**Comment by iliraga** [comment]
@casevictor I reconnect each time I want to resend stuff through a lazy apnConnection-Initializer. The old instance is usually killed by the GC because no reference to it can be found anymore then. So for each send-batch I reconnect to APNs... Jeah I know it's bad.

**Comment by casevictor** [comment]
@florianreinhart Do you have a clue about what going on with this socket problem ? Maybe it is a node bug?

**Comment by florianreinhart** [comment]
I have no idea. However, I have the feeling that the node-http2 module has some issues. We currently have to use custom fork that fixes a leak. A PR has been submitted, but not yet merged, see [PR200](https://github.com/molnarg/node-http2/pull/200) and [PR222](https://github.com/molnarg/node-http2/pull/222).

Once Node.js has official HTTP/2 support we will switch to that asap.

**Comment by florianreinhart** [comment]
@casevictor Could [this node-http2 issue](https://github.com/molnarg/node-http2/issues/224) be the reason for your initial issue?
