### ISSUE TITLE
ENOENT: no such file or directory, open 'key.pem'

### ISSUE THREAD

**Issue by jameshfisher** [node-apn/node-apn#455]
Here's my script:

``` javascript
var apn = require('apn');

var options = {
  cert: "cert_dev.pem",
  production: false
};

var apnProvider = new apn.Provider(options);
```

Running this throws the error:

```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'key.pem'
```

Looking at [the docs](https://github.com/node-apn/node-apn/blob/master/doc/provider.markdown), I see

> `key` {Buffer|String} The filename of the connection key to load from disk, or a Buffer/String containing the key data. (Defaults to: `key.pem`)

So `'key.pem'` comes from the default value of a `key` option in the options object.

My problem is that I don't know what to set `key` to. I don't know what the `key` option even represents. I don't know what a "connection key" is, and Google turns up nothing. It doesn't appear to be PKI terminology or APNs terminology.

When using [apns2](https://github.com/sideshow/apns2), an equivalent library in Go, I do not have to set anything like a "connection key", and so I assume it's not necessary for me to use this library, either. But I don't know how to tell the library that I don't have a connection key.

**Comment by florianreinhart** [comment]
APNs requires a certificate and the corresponding private key. See the wiki for information on how to create these in the correct format: https://github.com/node-apn/node-apn/wiki/Preparing-Certificates
