### ISSUE TITLE
"connectionTerminated" Error 

### ISSUE THREAD

**Issue by abhiCR7** [node-apn/node-apn#456]
I'm running my server in AWS. Notifications are being delivered intermittently(majority being dropped) with error code 515. 
I have set the connectionTimeout 2 min.
Can anyone please provide any info why this might be happening ?

**Comment by oliversalzburg** [comment]
> Can anyone please provide any info why this might be happening ?

Not really, based on the information you have provided. 515 is not a standard HTTP response and Apple is not sending it either, according to their docs.

**Comment by abhiCR7** [comment]
Thanks @oliver
 Yes. 515 is not returned by APN. If you see errors. Js file it's for 'connectionTerminated'  returned by library. So I'm not sure why the connection is being terminated.

**Comment by florianreinhart** [comment]
I am closing this issue because of insufficient information.
