### ISSUE TITLE
AssertionError in module http2

### ISSUE THREAD

**Issue by josemsanchiz** [node-apn/node-apn#458]
Good Morning!
First, sorry for my English. I have an app working for several weeks without problems. This app is capable of send Push messages to a multiple devices. Since few days ago i have an error messages and the app not send the push messages to all devices. I have this exit on my server console:

assert.js:89
  throw new assert.AssertionError({
  ^
AssertionError: false == true
    at Connection._send (/home/bitnami/aplicaciones/push_services/node_modules/http2/lib/protocol/connection.js:342:9)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

Can anyone help me, please?

Thank you in advance.

**Comment by oliversalzburg** [comment]
https://github.com/node-apn/node-http2/blob/master/lib/protocol/connection.js#L342 for anyone looking for the source.

**Comment by josemsanchiz** [comment]
Hi! Thanks!
But, why i have this error now? I don´t have it until now. Any update?

Thanks!

**Comment by oliversalzburg** [comment]
No idea, did you change anything? Did you upgrade Node? Install any other modules?

**Comment by josemsanchiz** [comment]
Nop, the only change is the number of tokens of users devices. We have 3 or 4 times more users than 2 weeks ago. 
Well, this morning I have updated this module, node-apn, but the error is there at this time.

**Comment by josemsanchiz** [comment]
Maybe a problem with the node version? Actually we have node 6.4.0. Have any known problem with this version?

**Comment by sidsonAidson** [comment]
I also got this issue. I downgraded to 1.7.8 version

**Comment by josemsanchiz** [comment]
Hey! Solved!
There´s any problem with the node version. I have downgraded the node version of our server to the 5.11.1 and works like a charm!
For if can help someone with the same error.

**Comment by recurrence** [comment]
I've been seeing this in node latest.  Larger user counts seem to be the culprit.

**Comment by mattisx** [comment]
Downgrading to an inferior node version isn't a solution in my opinion. Possibly node-apn need to adjust to a parent library change?
