### ISSUE TITLE
Question: Error codes

### ISSUE THREAD

**Issue by m1ome** [node-apn/node-apn#460]
Hi, can anyone paste a link to all error codes?
I mean i want remove "wrong" token i have in my DB but don't see any links about error codes.
And i don't know what error codes i should resolve as "bad/invalid token" code.

Thank you.
This is a question, not a bug.

**Comment by oliversalzburg** [comment]
https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW2
