### ISSUE TITLE
node.js v6 -> v7 = DeprecationWarning 

### ISSUE THREAD

**Issue by Eliaschetouani** [node-apn/node-apn#462]
(node:52979) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

**Comment by florianreinhart** [comment]
Thanks @Eliaschetouani.

We don't use `Buffer()` without `new` in node-apn. I only found four `Buffer()` usages in the client test case. So this warning is caused by another node module.
