### ISSUE TITLE
PushKit support

### ISSUE THREAD

**Issue by merajmehrabi** [node-apn/node-apn#464]
This wonderful node-apn should support PushKit very soon.

**Comment by Slessi** [comment]
Would this be related to the error "UNABLE_TO_GET_ISSUER_CERT_LOCALLY" ?

I tried updating from 1.7.6 to 2.1.2 and I notice the [voip option](https://github.com/node-apn/node-apn/blob/v1.7.6/lib/connection.js#L50) has been removed from the new apn.Provider (previously apn.Connection) and my previously working project now throws that error at me when I try to send a notification.

**Comment by florianreinhart** [comment]
@Slessi I don't think this is related. A 4KB payload was only supported for VoIP notifications. But now all notifications can have a payload of up to 4KB. So when the voip flag was set, we increased the max payload size to 4KB.

@merajmehrabi What is required to support PushKit?

**Comment by erva-** [comment]
@merajmehrabi I got it working with pushkit just fine.  There were two things I had to do.

- append the notification.topic with ".voip" 
(i.e. from "com.example.app" to "com.example.app.voip")

- use the token returned from pushkit as the device token.

**Comment by astanton** [comment]
Thank you for the answer @erva- I just spent about 4 hours pulling my hair out wondering why pushkit wasn't working through using node-apn but I could send them fine with the houston CLI.  I added .voip to the topic and it worked no problem!

**Comment by nickmendes** [comment]
@merajmehrabi Thanks for the answer mate 👍
