### ISSUE TITLE
SyntaxError: Unexpected token on line 28 : /node_modules/apn/index.js:28

### ISSUE THREAD

**Issue by sivapc** [node-apn/node-apn#466]
/node_modules/apn/index.js:28
	tls,
	   ^
SyntaxError: Unexpected token ,

Can you help me fixing the issue?

**Comment by r0stig** [comment]
@sivapc What version of Node are you running?

**Comment by sivapc** [comment]
Node version is : v0.10.25

**Comment by florianreinhart** [comment]
node-apn requires node v4 or greater. I suggest updating to an LTS release, node v4 or better v6: https://github.com/nodejs/LTS#lts-schedule

**Comment by sivapc** [comment]
@florianreinhart : Thanks for your reply, I will update the version and check.
