### ISSUE TITLE
Does it work with updating Apple's wallet passes ? 

### ISSUE THREAD

**Issue by nemr** [node-apn/node-apn#469]
Hi , Im trying to establish a push notification in order to update a pass on apple's wallet .
However , Im not sure how to do that using this module (what should I include ?)

I know that I need to use my passID along with the push token which I got from apple's API once my device was registered ([details here](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/PassKit_PG/Updating.html#//apple_ref/doc/uid/TP40012195-CH5-SW1) )
this is what I have done so far : 
```

var apn = require('apn');

var fs = require('fs');

var options = {
    production: false,
key: "/Users/Desktop/codetest/keys/key.pem", // this is my PassID type ID Certificate 
passphrase:"1234",

};

var apnProvider = new apn.Provider(options);
let deviceToken = "push token which i got from registering the device which has the pass";
var note = new apn.Notification();

note.payload = {};

apnProvider.send(note, deviceToken).then( (result) => {
    // see documentation for an explanation of result
   
});
```

I'm getting the following error 
```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'cert.pem'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
```

So im not sure if this is the correct way to do it or should I include my WWDR certificate as well ? 

an example of using this module for updating passed would be very helpful :) :
many Thanks

**Comment by florianreinhart** [comment]
The recommended way ist to use JSON Web Tokens for authentication, see [Provider Authentication Tokens ](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1) and also the [Provider Documentation](https://github.com/node-apn/node-apn/blob/master/doc/provider.markdown).

If you want to use the "old" way with certificate authentication, you also have to provide a cert in your options. It defaults to `cert.pem` and fails to open that file in your code. See [Preparing Certificates](https://github.com/node-apn/node-apn/wiki/Preparing-Certificates) for more information on how to create key and cert.

**Comment by nemr** [comment]
Thanks for the quick replay , I dont think that the passes supports JWT since there was no update on obtaing such tokens in thier documentation . The only keys they said were required are the ones for the passType ID. I noticed that the pem i provided as a key had both a certificate and a key so I rectified it by converting the .p12 into a certeficate and a key pem 

```
var apn = require('apn');

var fs = require('fs');


var options = {
    production:false ,
    cert:'/Users/Desktop/codetest/keys/newfile.crt.pem',                 /* Certificate file path */
    key: '/Users/Desktop/codetest/keys/newfile.key.pem',                  /* Key file path */
    passphrase:"1234",                 /* A passphrase for the Key file */
    gateway: 'gateway.sandbox.push.apple.com',/* gateway address */
    port: 2195,                       /* gateway port */
};

var apnProvider = new apn.Provider(options);
let deviceToken = "push token";
var note = new apn.Notification();
note.payload = {};

apnProvider.send(note, deviceToken).then( (result) => {
    // see documentation for an explanation of result
   console.log("dd");
});
```
I get the following 
```
s:19
			throw new Error("certificate does not support configured environment, production: " + credentials.production);
			^

Error: certificate does not support configured environment, production: false
    at validateCredentials 
```
when i change it to production true , the programme runs but nothing gets written in the results plus I'm not working on production atm 

any suggestions ?

**Comment by florianreinhart** [comment]
The APNs client certificates are tied to either the production or development environment. You are apparently using a production certificate. You have to create a separate development certificate in the member center.

Nevertheless, I would try using JWT. I think it'll work with PassKit as well and makes things much simpler.

**Comment by nemr** [comment]
Will give it a go , Thanks for your support

**Comment by nemr** [comment]
Didn't really work with the JWT 
```
var apn = require('apn');

var options = {
    token: {
        key: "/Users/Desktop/codetest/keys/apn.p8",
        keyId: "********",
        teamId: "*******",
    },
    production: true,
};


var apnProvider = new apn.Provider(options);
let pushToken = "********";
var note = new apn.Notification();
note.payload = {};
apnProvider.send(note, pushToken).then( (result) => {
    
    console.log(result);
    
```
I get 
```
});

  failed: 
   [ { device: '******',
       status: '400',
       response: [Object] } ] }
```

**Comment by florianreinhart** [comment]
Is the device token (`pushToken` in your code) a token from a production release of your app? Probably not...

Device tokens a tied to either the production or development environment. Also, inspecting the actual response from APNs should give you a hint what's wrong.

**Comment by nemr** [comment]
I'm not working on an app , I'm trying to update the pass through a server , based on apple's documentation, they register the device which has added the pass to its wallet and provide me with a pushToken.  so that when I need to update the pass , I have to send a push notification which has PassType ID and the Push Token along with an empty JSON 

This is what I'm trying to do  :

![screenshot 2016-11-10 15 28 27](https://cloud.githubusercontent.com/assets/13883518/20220007/c6d0e01a-a823-11e6-9666-f6c3c415ccfb.png)

> Your server sends the following pieces of information:
> 
> The pass type identifier (in the certificate)
> The push token (in the communication to the Apple Push Notification service)
To send the push notification, do the following:

> To send the push notification, do the following:
> 
> Update the passes table with the new pass information, and get the pass type identifier and serial number for the pass that changed.
> Consult the registrations table, and get the list of devices that registered for updates for that pass.
> Consult the devices table, and get the push token for each device.
> Send a push notification with an empty JSON dictionary as its payload to each push token.

So if there is way To do this using this module please do let me know

**Comment by florianreinhart** [comment]
Alright, I see. I've never used PassKit myself, so I cannot help you in that case. But from glancing at the documentation this is possible with node-apn, since it is based on APNs.

**Comment by nemr** [comment]
Thanks , will keep on trying to see if it works out

**Comment by bayareacoder** [comment]
Nemr, did you get this to work? If so, how?

**Comment by henkvanderspek** [comment]
@nemr @bayareacoder Any solutions for this? I'm facing similar issues. Tried with both JWT and old style signing, both ways I was unable to send pass updates using apns.

**Comment by laura-levelup** [comment]
Just wanted to weigh in to say that while I'm not using node-apn, I came across this thread while building an integration with the ruby gem apnotic.  I wanted to confirm that I was able to send push notifications using the new HTTP/2 provider api to update passes, and both forms of authentication (token based or certificate based) worked.  To make token-based authentication work, I had to set the push notification topic to be the Pass Type ID.

**Comment by laura-levelup** [comment]
@velchev Using the new HTTP/2 provider api, you can use either form of authentication (token based or certificate based).

If you use token based, you can use 1 key for all topics (a topic will be either an app bundle id or pass type id).  To create this key, you want to go to the "Create a Key" page, not "Add iOS Certificate" page.  This article outlines the steps: https://developer.clevertap.com/docs/how-to-create-an-ios-apns-auth-key

If you use certificate based, you need a separate certificate for each app.  And according to Apple's [documentation](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Updating.html#//apple_ref/doc/uid/TP40012195-CH5-SW1), "You use the same certificate and private key for sending push notifications as for signing passes."

As for how to communicate with the http/2 provider API, I recommend looking at their [documentation](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1).

**Comment by limparty** [comment]
I used cer file of pass type identify to create p12 and pem file. if you need detail, email me limparty [at] gmail.com

**Comment by Dicondur** [comment]
Thanks for the info @laura-levelup

I tried using token for APN and I get a "sent" response:

**APN info:**
` var apnProvider = new apn.Provider({
token: {
key: AuthKey_xxx.p8", // Path to the key p8 file
keyId: "xxx", // The Key ID of the p8 file
teamId: "nnn", // The Team ID of your Apple Developer Account
},
production: true,
});

var notification = new apn.Notification();
notification.topic = passTypeIdentifier;
notification.payload = { };`

**Response:**
`
{
"sent": [
{
"device": "8cxxxxxxxxxxxxx4"
}
],
"failed": []
}`

But dont get to see notification from the wallet app. 
I have ChangeText field on all fields on the pass. I have errors on PassKit log post call.
I have checked all options on the phone to get notifications and on the pass itself.

Also apnProvider.shutdown(); doesnt work with active coonection so I had to post an invalid device ID to come out to do apnProvider.shutdown(). For this entry alone I have a PK log post.
Is there anything else I cloud check for notificationsto work?


Much appreciate it!

**Comment by stackcru-tech** [comment]
> Thanks for the info @laura-levelup
> 
> I tried using token for APN and I get a "sent" response:
> 
> **APN info:**
> ` var apnProvider = new apn.Provider({
> token: {
> key: AuthKey_xxx.p8", // Path to the key p8 file
> keyId: "xxx", // The Key ID of the p8 file
> teamId: "nnn", // The Team ID of your Apple Developer Account
> },
> production: true,
> });
> 
> var notification = new apn.Notification();
> notification.topic = passTypeIdentifier;
> notification.payload = { };`
> 
> **Response:**
> ` { "sent": [ { "device": "8cxxxxxxxxxxxxx4" } ], "failed": [] }`
> 
> But dont get to see notification from the wallet app.
> I have ChangeText field on all fields on the pass. I have errors on PassKit log post call.
> I have checked all options on the phone to get notifications and on the pass itself.
> 
> Also apnProvider.shutdown(); doesnt work with active coonection so I had to post an invalid device ID to come out to do apnProvider.shutdown(). For this entry alone I have a PK log post.
> Is there anything else I cloud check for notificationsto work?
> 
> Much appreciate it!

had you resolved the issue?

**Comment by juanpgaviria** [comment]
@stackcru-tech @Dicondur 

> > Thanks for the info @laura-levelup
> > I tried using token for APN and I get a "sent" response:
> > **APN info:**
> > ` var apnProvider = new apn.Provider({
> > token: {
> > key: AuthKey_xxx.p8", // Path to the key p8 file
> > keyId: "xxx", // The Key ID of the p8 file
> > teamId: "nnn", // The Team ID of your Apple Developer Account
> > },
> > production: true,
> > });
> > var notification = new apn.Notification();
> > notification.topic = passTypeIdentifier;
> > notification.payload = { };`
> > **Response:**
> > ` { "sent": [ { "device": "8cxxxxxxxxxxxxx4" } ], "failed": [] }`
> > But dont get to see notification from the wallet app.
> > I have ChangeText field on all fields on the pass. I have errors on PassKit log post call.
> > I have checked all options on the phone to get notifications and on the pass itself.
> > Also apnProvider.shutdown(); doesnt work with active coonection so I had to post an invalid device ID to come out to do apnProvider.shutdown(). For this entry alone I have a PK log post.
> > Is there anything else I cloud check for notificationsto work?
> > Much appreciate it!
> 
> had you resolved the issue?

@stackcru-tech @Dicondur have you resolved the issue?

**Comment by vartana** [comment]
This should be reopened. The issue still exists, I can update the wallet card but the notification does not show up.

**Comment by adhambadr** [comment]
Apple Wallet notifications are silent by design (according to their documentation) the notification forces the device to re-ping your webserviceurl `/v1/devices/[...params]` to fetch the new version. 

Here is a working code to make it work using the the same .pem file you signed the pass with

 Add 2 Environment variables by opening the .pem file and copying the '---begin ceritficate ... --- end certificate--' part and converting it to base 64 (in osx terminal: pbpaste | base64 | pbcopy)  and do the same for the part '---BEGIN ENCRYPTED KEY ... Private KEY ---- '
`WALLET_PEM_CERTIFICATE= base64 of certificate part`
`WALLET_PEM_PRIVATE_KEY= base64 of private key`

```js
//const token = <unique device token you received from Apple servers> 
const options = {
  cert: Buffer.from(process.env.WALLET_PEM_CERTIFICATE, "base64").toString("utf8"),
  key: Buffer.from(process.env.WALLET_PEM_PRIVATE_KEY, "base64").toString("utf8"),
  passphrase: process.env.WALLET_SECRET,
  production: true,
};
const provider = new apn.Provider(options);
const not = new apn.Notification();
not.topic = process.env.WALLET_IDENTIFIER;
provider.send(not, token).then(console.log).catch(console.error);
```

**Comment by leszekbulawa** [comment]
> Apple Wallet notifications are silent by design (according to their documentation) the notification forces the device to re-ping your webserviceurl `/v1/devices/[...params]` to fetch the new version.
> 
Hey @adhambadr, I know it's beed a while but can you please point me the docs? I cannot find anything about Apple Wallet notifications being silent by design, but apparently it works that way. I developed a web app having in mind that I can use Wallet for notifications but it looks like it's not possible. Now I'm looking official confirmation for that.
Thanks!

**Comment by limparty** [comment]
what language (web app) do you use?



-----------------------------------

ขอแสดงความนับถือ
นายสิทธิชัย รัตนเกียรติสกุล (ลิ้ม)
หัวหน้าฝ่ายปฏิบัติการ
บริษัท เอส.วาย. โซลูชั่น จำกัด
TEL: 08 9922 1652
Website: http://www.sysolutions.co.th
Email: ***@***.***, ***@***.***

**Comment by kunj404** [comment]
Hey @leszekbulawa , I am at the same point as you are. going to dig up this weekend. but i do have some reference for this. idk if this works but just give it a try
https://stackoverflow.com/questions/78735804/custom-push-notification-for-apple-wallet-pass-not-showing-up-on-phone
