### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY after upgrading from 1.7.6 to 2.1.2

### ISSUE THREAD

**Issue by Slessi** [node-apn/node-apn#472]
After upgrading my node-apn to `2.1.2`, I am no longer able to send notifications.
On `1.7.6` my configuration worked.

Node version `4.6.0`
NPM version `2.15.9`

Error is `UNABLE_TO_GET_ISSUER_CERT_LOCALLY`.

> **Note**: I don't think I can use the JWT method as I use PushKit notifications (and as such,  a VoIP certificate) and it doesn't seem like the APN auth key supports this

The following sample code reproduces the issue:

```javascript
var apn = require('apn');

var config = {
  production: false,
  key: 'conf/apn/key.pem',
  cert: 'conf/apn/cert.pem', // This is a VoIP services certificate
  ca: 'conf/apn/ca.pem'
};

var apnProvider = new apn.Provider(config);
var notification = new apn.Notification();
var apnToken = apn.token('token');

notification.topic = 'com.bundle.id';

apnProvider.send(notification, apnToken).then(onNotificationsSent);

function onNotificationsSent (deliveries) {
  deliveries.failed.forEach(deliveryFail);

  function deliveryFail (failure) {
    // endpoint error: unable to get local issuer certificate when sending to 'token'
    console.log(`${failure.error.message} when sending to '${failure.device}'`);
  }
}
```

Config options as seen in `Endpoint.prototype._connect` (error first thrown at [this line](https://github.com/node-apn/node-apn/blob/master/lib/protocol/endpoint.js#L78)). The certificates were found (I've removed the buffer `data` keys for brevity).

```json
{
  "token": null,
  "cert": {
    "type": "Buffer",
    "data": [...]
  },
  "key": {
    "type": "Buffer",
    "data": [...]
  },
  "ca": [
    {
      "type": "Buffer",
      "data": [...]
    }
  ],
  "pfx": null,
  "passphrase": null,
  "production": false,
  "address": "api.sandbox.push.apple.com",
  "port": 443,
  "rejectUnauthorized": true,
  "connectionRetryLimit": 10,
  "host": "api.sandbox.push.apple.com",
  "servername": "api.sandbox.push.apple.com",
  "ALPNProtocols": [
    "h2"
  ]
}
```

**Comment by Slessi** [comment]
It appears my problem has been resolved by removing the `ca.pem` from config and not setting `notification.topic`.

Removing `ca.pem` halted the error and resolved an an HTTP 400 with reason `TopicDisallowed`. Not sure whats up with this as I don't have the CA included in my `cert.pem` and I thought topic was a required value, but maybe VoIP is different.

**Comment by florianreinhart** [comment]
`topic` is required for JWT authentication only.

`ca` is used to verify Apple's server certificate. In general you don't need to set `ca`, because your system already trusts Apple's certificate.

**Comment by Slessi** [comment]
Thank you :)
