### ISSUE TITLE
Feedback Service

### ISSUE THREAD

**Issue by SeungyuLee** [node-apn/node-apn#473]
How can I get APNs feedback service although apn.Feedback has been removed?

does apn.Provider method provide that kind of function?

**Comment by SeungyuLee** [comment]
console.log(`Sending: ${note.compile()} to ${tokens}`);
service.send(note, tokens).then( result => {
    console.log("sent:", result.sent.length);
    console.log("failed:", result.failed.length);
    console.log(result.failed);
});

I can get direct feedback from APNs with the code above, but I need to get APNs feedback service  which occurs when APNs sends push notification to devices (power off, app uninstalled, etc.)

**Comment by florianreinhart** [comment]
This is not possible and also wasn't possible with the old feedback service.
