### ISSUE TITLE
token credentials

### ISSUE THREAD

**Issue by j4nos** [node-apn/node-apn#474]
@florianreinhart could you explain what is the 3 token parameter? key:  location of the certificate file. But what is "keyId" and "teamId" and when they need?

**Comment by florianreinhart** [comment]
Please read Apple's documentation: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1

**Comment by ademcan** [comment]
I am sorry to bring this thread back to life, but I really cannot find my keyId, although I read the documentation you are refering. I can see the certificate on my Keychain Access app but cannot find anything like key ID? Thank you.

**Comment by sidsonAidson** [comment]
Login here https://developer.apple.com/account/#/membership
You will get you to your Membership Details( scroll down to Team ID)

**Comment by ademcan** [comment]
Thank you @sidsonAidson, I already found the TeamID, but I cannot find the keyID, do you know where I can find this information?

**Comment by sidsonAidson** [comment]
you have to generate new certification from developer console .Certificate for "Apple Push Notification token-based authentication" and you will get a file named in this format:
APNSAuthKey_XXXXXXX.p8 where XXXXXX is your keyID

**Comment by ademcan** [comment]
Thank you very much @sidsonAidson :D I finally found it. 
In case anybody else has the same issue: you have to choose the following option when generating a new certificate from your developer console "Apple Push Notification Authentication Key (Sandbox & Production)".
