### ISSUE TITLE
key.p8

### ISSUE THREAD

**Issue by j4nos** [node-apn/node-apn#476]
How do you generate the file is located in "path/to/key.p8"? In "Preparing Certificates" section a "cert.pem" and a "key.pem" is created.

https://github.com/node-apn/node-apn/wiki/Preparing-Certificates

Which certificate file I need to feed the script with?

**Comment by oliversalzburg** [comment]
[This might work](http://stackoverflow.com/questions/8290435/convert-pem-traditional-private-key-to-pkcs8-private-key):
```shell
openssl pkcs8 -topk8 -inform PEM -outform DER -in filename -out filename -nocrypt
```

**Comment by j4nos** [comment]
@oliversalzburg input file is the .p12 file?

**Comment by oliversalzburg** [comment]
After reviewing that Wiki page, I don't even see any reference to a `.p8` file.

**Comment by joachimboggild** [comment]
You can get the key on the apple developer site:

<img width="269" alt="apns_key" src="https://cloud.githubusercontent.com/assets/8225312/20380437/599a767c-aca2-11e6-82bd-3cbfc2feee33.png">

**Comment by j4nos** [comment]
I know `keyId`, and `teamId`, but `key` I do not know. I tried generate different kind of PEM i certificate files based on the Wiki but none of them works. What is wrong?

var options = {
  token: {
    key: "path/to/key.p8",
    keyId: "T0K3NK3Y1D",
    teamId: "T34M1D",
  },
  production: false,
};

**Comment by florianreinhart** [comment]
APNs has to ways for authentication:
* Provider Authentication Tokens a.k.a. JSON Web Tokens (JWT)
* Provider Certificates

You are trying to use JWT with a provider certificate, which will not work.

Please read the part on Provider Authentication Tokens in [Apple's documentation](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html). You have to download a .p8 file from the Developer Portal.

**Comment by zhouhao27** [comment]
Is there a way to convert p12 to p8? I only have a p12 file and I don't have access to Apple Developer account.

**Comment by oliversalzburg** [comment]
@zhouhao27 I thought that's what this thread is about
