### ISSUE TITLE
InvalidProviderToken

### ISSUE THREAD

**Issue by j4nos** [node-apn/node-apn#477]
When sending message like in tutorial below, I get error: `response: { reason: 'InvalidProviderToken' } }` Any idea what I am doing wrong?

Apple says: `APNs supports only provider authentication tokens that are signed with the ES256 algorithm. Unsecured JWTs, or JWTs signed with other algorithms, are rejected, and your provider server receives the InvalidProviderToken (403) response.`

https://eladnava.com/send-push-notifications-to-ios-devices-using-xcode-8-and-swift-3/

**Comment by joachimboggild** [comment]
You can get a valid provider token on the Apple developer site, members section.

https://developer.apple.com/account/ios/certificate/

**Comment by winter7621** [comment]
Make sure you are using the correct **team ID** and **key ID**

**Comment by nalogowiec** [comment]
@winter7621 I found **team ID** on apple dev website in the membership section, but I cannot locate anywhere **key ID**, can you tell me where to find it?

**Comment by sidsonAidson** [comment]
@winter7621 you have to generate new certification from developer console .Certificate for Apple Push Notification token-based authentication".
Just choose `Apple Push Notification Authentication Key (Sandbox & Production)`and you will get a file named in this format:
APNSAuthKey_XXXXXXX.p8 where XXXXXX is your keyID

**Comment by brianfoody** [comment]
This was a helpful article for me. You will get your key id at the end of it.

http://gobiko.com/blog/token-based-authentication-http2-example-apns/

Look in the Membership section then for the Team Id like you said.
