### ISSUE TITLE
apn@2.1.0 not working on Linux

### ISSUE THREAD

**Issue by liaolunhui** [node-apn/node-apn#478]
![image](https://cloud.githubusercontent.com/assets/13741751/20553118/6a101d2e-b18c-11e6-9f8a-9f1b277b5e0e.png)
I try ubuntu 14.04 and CentOs 7,apn@2.1.0 not working.
But apn@1.7.8 working fine.

**Comment by florianreinhart** [comment]
What node version are you running?

**Comment by liaolunhui** [comment]
v5.7.0 on Ubuntu 14.04 and v5.7.1 on  CentOs 7

**Comment by florianreinhart** [comment]
Node v5 isn't supported anymore. Please update to node v6, see [LTS Schedule](https://github.com/nodejs/LTS#lts-schedule)

Also, please use the latest node-apn version v2.1.2.

**Comment by liaolunhui** [comment]
Ok , but the `pm2` and `node-inspector` not working fine after node v6. So I perfer to use apn@1.7.8 .

**Comment by florianreinhart** [comment]
Do as you please. But I wouldn't run an old unsupported node version from Feburary 2016 in production 😉

**Comment by liaolunhui** [comment]
thank you a lot

**Comment by mast** [comment]
Gentelmen, BTW, I'm running node-apn v2.1.2 with Node v.5.12.0 on Ubuntu 14.04, and all works just fine. I don't see such a problem.
