### ISSUE TITLE
Node engine version

### ISSUE THREAD

**Issue by Biktop** [node-apn/node-apn#482]
I've noticed that you changed minimum node engine version from 4.0.0 (2.1.2) to 4.6.0 (2.1.2). I think it was quite bold for minor version. Was it some necessary thing or just technical update?
I use this component in AWS Lambda and it supports only 4.3. 

Is it possible to return back the minimum version of node engine?

**Comment by oliversalzburg** [comment]
4.6 is LTS, 4.0 isn't.

**Comment by Biktop** [comment]
I know but unfortunately Amazon (AWS Lambda) supports only 4.3

**Comment by florianreinhart** [comment]
This is indeed for technical reasons, we are using features which are only present in 4.6+.

**Comment by Biktop** [comment]
I understand but you've broken compatibility in minor version (from 2.1.1 to 2.1.2).
