### ISSUE TITLE
ThreadId should be in APS dictionary

### ISSUE THREAD

**Issue by n3trino** [node-apn/node-apn#484]
The **thread-id** should be part of the aps dictionary as stated [here](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW1) (see Table 9.1) and not in the request [header](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1) (see Table 8.2).

In the current implementation **thread-id** is treated as request header:

`Notification.prototype.headers = function headers() {
	let headers = {};

	if (this.priority !== 10) {
		headers["apns-priority"] = this.priority;
	}

	if (this.id) {
		headers["apns-id"] = this.id;
	}

	if (this.expiry > 0) {
		headers["apns-expiration"] = this.expiry;
	}

	if (this.topic) {
		headers["apns-topic"] = this.topic;
	}

	if (this.collapseId) {
	  headers["apns-collapse-id"] = this.collapseId;
	}

	if (this.threadId) {
		headers["thread-id"] = this.threadId;
	}

	return headers;
};`

**Comment by n3trino** [comment]
Will be released as part of new version, soon?

**Comment by jchambers** [comment]
Hello! I'm the main author of [Pushy](https://github.com/relayrides/pushy), an APNs library for Java. We're just getting around to [adding support for `thread-id`](https://github.com/relayrides/pushy/issues/382) (oops), but are having a hard time verifying that our changes are actually having an effect. @florianreinhart If you have a moment and wouldn't mind providing some advice, I was curious about how you've verified these changes.

Like you've just done in dea8951, we're adding `thread-id` to the `aps` section of the payload. What behavior change do you observe when sending notifications with a `thread-id` header? I haven't been able to spot any changes to message ordering or appearance in my phone's Notification Center in testing. In particular, I've been alternating sending messages with and without a thread ID, but they all seem to just appear serially in the order in which they were received. Have you seen something different?

Thanks very much for your time!

**Comment by n3trino** [comment]
@florianreinhart will this fix pushed in a new version?? The latest available is v2.1.2 which released at 8 November and this is not included.
