### ISSUE TITLE
Documentation issue?

### ISSUE THREAD

**Issue by trx222** [node-apn/node-apn#487]
Hi, I think there is an issue in  **/doc/whats-new.markdown**

in sample code for Version 2.0, in the **response.failed.forEach** - Loop its used **token** but, token is unknown there. I think it should be **failure.device** instead, isn't?

And a quick question ... how many recivers can be handled in an array for one send-call? Didn't found infos right now.

thanks for the lib!

**Comment by florianreinhart** [comment]
Your are correct. I fixed the example.

There is no limitation on the number of receivers.
