### ISSUE TITLE
Mutable-content in wrong place?

### ISSUE THREAD

**Issue by n3trino** [node-apn/node-apn#488]
In the [Notification documentation](https://github.com/node-apn/node-apn/blob/master/doc/notification.markdown), the example with **mutable-content**, points out that the mutable-content key is part of the alert dictionary. In [Apple's documentation](https://developer.apple.com/reference/usernotifications/unnotificationserviceextension) says that **mutable-content** key is part of aps dictionary. So is it just a typing mistake or there is a bug in the code which sends **mutable-content** in the wrong place? I couldn't figure out by reviewing the code.

**Comment by florianreinhart** [comment]
The example in our documentation is wrong. I'll fix it.
