### ISSUE TITLE
abort & disconnect when `.send` timeout

### ISSUE THREAD

**Issue by magicdawn** [node-apn/node-apn#492]
I set a timeout for a `provider.send` call, when this timeout, I want to completed destroy the connection, and abort the `.send`, cause I will create a new instance to send this.
If I do not abort, this notification may be sent twice here, and if the tcp connection was not destroyed, this will cause too many opened fds problem.

So what should I need to do, just `provider.destroy()` , or should I do a small trick, empty the queue ?

**Comment by florianreinhart** [comment]
Could you explain what your use case is?

Calling `provider.shutdown()` shuts down the connection after emptying the current queue.

**Comment by florianreinhart** [comment]
@magicdawn I am closing this. If you still have any questions, feel free to reply to this issue.

**Comment by magicdawn** [comment]
Hello, sorry for forgetting this

Here is my concern, I set a timeout for a Notification Push. and when the timeout exceed, I need to retry. so I need to abort the timeout-exceeded push, no matter in what way. The retry may utilize another connection.

**Comment by magicdawn** [comment]
The purpose is try not to send multi times for a notification multi times

**Comment by florianreinhart** [comment]
There should be no need to implement a custom retry in that way. The callback will called if sending fails and you can then retry.

What are you trying to achieve with this timeout?

**Comment by magicdawn** [comment]
A flow control. I'm using a single push once, and with a concurrency limit, after single push complete, the worker is idle to deliver another push. Actually I'm using rabbitmq, and 100 consumer, 1 node-apn Provider per consumer. After the `push` success or fail or timeout exceed, the consumer will ack the queued notification. So A timeout is need.

And Pour all notifications to the memory will blow the node application. And it's also not easy to have persistence.

**Comment by oliversalzburg** [comment]
100 instances of node-apn? O___O How many devices are in your user base?

**Comment by magicdawn** [comment]
@oliversalzburg 30k, since a single apn.Provider cause problems, like #449 #471 , I change the number to 100
