### ISSUE TITLE
How to change badge number on a message for multiple recipients (one provider.send per recipient) ?

### ISSUE THREAD

**Issue by iwllyu** [node-apn/node-apn#495]
I need to change the badge number on the message depending on the recipient. Due to how notifications get compiled the only workaround I can think of is creating a new message for each recipient. This seem like much wasted overhead as the content of every message is identical except for the badge number.

I tried copying the message (with lodash.merge) but due to how the object is structured changes to the copy's badge do not reflect in the built notification after compile

I think ideally the aps.send should take a badge parameter so it can adjust the badge for each send. notification.compile would have to have an option to force compiling instead of using the cached compile.

**Comment by florianreinhart** [comment]
You have to create a separate message for each badge count.
