### ISSUE TITLE
node-apn will not run in AWS Lambda

### ISSUE THREAD

**Issue by PatonLewis** [node-apn/node-apn#497]
AWS Lambda currently only supports Node 4.3, but endpoint.js uses Buffer.from, which was introduced in Node 6. The solution appears to be to change the call Buffer.from(foo) to Buffer(foo).

**Comment by florianreinhart** [comment]
`Buffer.from()` is available in the node v4 LTS release. Can you point me to the AWS Lambda documentation?

**Comment by oliversalzburg** [comment]
[Buffer.from was added in 5.1](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array) apparently.

**Comment by florianreinhart** [comment]
Nope, it's available in 4.5: https://nodejs.org/dist/latest-v4.x/docs/api/buffer.html#buffer_class_method_buffer_from_array

**Comment by oliversalzburg** [comment]
Well, those are some conflicting docs :D

**Comment by chartotu19** [comment]
@florianreinhart is there a planned fix for node-apn to run on AWS lambda? `Buffer.from` was introduced in v4.5 as you mentioned. AWS lambda currently supports v4.3 only.

**Comment by oliversalzburg** [comment]
@chartotu19 How about this? https://www.npmjs.com/package/buffer-v6-polyfill

**Comment by florianreinhart** [comment]
@PatonLewis @chartotu19 have you tried @oliversalzburg's suggestion?

**Comment by chartotu19** [comment]
@florianreinhart unfortunately it didnt work for me. The polyfill is essentially overriding Buffer.from https://github.com/Daplie/node-buffer-v6-shim/blob/master/index.js#L26
```javascript
  Buffer.from = function(){
       return new Buffer(data, encoding, len);
 }
```
When i use the polyfill, my code hits the warning message.
https://github.com/Daplie/node-buffer-v6-shim/blob/master/index.js#L37
After doing console.log(e) on line 36, i got this. 
```
[TypeError: Cannot assign to read only property 'from' of function Buffer(arg, encoding) {
  // Common case.
  if (typeof arg === 'number') {
    // If less than zero, o...<omitted>...
}]
```
Any ideas?

**Comment by chartotu19** [comment]
it works for me now with buffer-v6-polyfill. I had to make a [small change](https://github.com/Daplie/node-buffer-v6-shim/compare/master...chartotu19:master) in the way `from` method was replaced in native Buffer object.

I got the idea from this polyfill script which also work btw. https://gist.github.com/yyang/f88c4cfa49daa6db2f4855d018aadbdc.

**Comment by PatonLewis** [comment]
@florianreinhart , I have not tried @oliversalzburg 's suggestion. I was able to address our immediate needs by changing the call Buffer.from(foo) to Buffer(foo) in our local copy of node-apn, so we have a work-around for now. Obviously we'll have to patch our local copy every time we update the package, at least until you land on a compatibility fix that you're happy with or Amazon upgrades their support for Node.js.

**Comment by kondratk** [comment]
I've got also an issue with AWS Lambda. I've installed node-apn, pushed zip to Lambda which includes my js file, node_modules, and package.json. Here is what I get:

```
module initialization error: TypeError
    at Function.from (native)
    at Object.<anonymous> (/var/task/node_modules/apn/lib/protocol/endpoint.js:17:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/task/node_modules/apn/index.js:27:18)
    at Module._compile (module.js:409:26)
```

Locally everything works fine.

**Comment by gligorkot** [comment]
Hi guys, I've run into the same issue, any reason for not just using `Buffer` instead of `Buffer.from` in `/lib/protocol/endpoint.js:17`? Would really help us out if we can run this in an AWS Lambda.

**Comment by mehulsutariya** [comment]
AWS now supports Node 6.10, so this should not be an issue after upgrading
https://aws.amazon.com/about-aws/whats-new/2017/03/aws-lambda-supports-node-js-6-10/
