### ISSUE TITLE
Wrong commands to generate .pem file in the Preparing Certificates tutorials  

### ISSUE THREAD

**Issue by montaserfzy** [node-apn/node-apn#498]
Please replace this command  

openssl x509 -in cert.cer -inform DER -outform PEM -out cert.pem
This command show wrong result and not working with me and others 

**Replace by this command** 
openssl pkcs12 -in key.p12 -out cert.pem -nodes -clcerts

**Comment by samsonho** [comment]
Just a correction to the replacement command. I believe it should be.
openssl pkcs12 -in key.p12 -out key.pem -nodes -clcerts

The required changes are due to changes to OpenSSL.

**Comment by florianreinhart** [comment]
I just used the "old" commands to generate certificates. They worked fine on macOS Sierra.

**Comment by abducbk** [comment]
What is keyId and teamId? key should be .p12 file or p8 file?

**Comment by florianreinhart** [comment]
The commands still work for me. I am closing this issue now.
