### ISSUE TITLE
Which way i can get the id of the sent notifications?

### ISSUE THREAD

**Issue by Snap974** [node-apn/node-apn#499]
Hi, I'm looking for a way to get the Id of the sent notification.

When I'm trying to get an Id is undefined.

> var note = new apn.Notification();
> 
> console.log(note.id) is undefined.
> 

Can you help me please? 

Have a nice day.

**Comment by jpwilliams** [comment]
According to [the docs](https://github.com/node-apn/node-apn/blob/master/doc/notification.markdown#notificationid), it should indeed be under the `id` property.

Definitely logging out the right variable? You're logging out `node` instead of `note` in your example there. :)

**Comment by Snap974** [comment]
Sorry, it's a typing error :). I was updated my comment.
```
 var note = new apn.Notification();
  note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
  note.badge = 3;
  note.sound = 'ping.aiff';
  note.alert = message;
  note.payload = {'messageFrom': 'Test'};
  note.clearBadge = true;
  console.log(note.id);
  var iosTokensFinish = [];
  listToken.forEach(function (item) {
    iosTokensFinish.push(item.token);
  });
  connection.send(note, iosTokensFinish).then(function (response) {
    response.sent.forEach(function (token) {
      notificationSent(token, note, listToken);
    });
    response.failed.forEach(function (failure) {
      console.log('failed: ', failure);
      if (failure.error) {
        notificationError(failure, failure.error);
      } else {
        notificationFailed(failure, failure.status, failure.response, note);
      }
    });
  });
```

I copy/paste my code :).

**Comment by jpwilliams** [comment]
Try logging out `note.id` _after_ sending? It may be that it only populates it upon sending (which would make sense given the way it lets you build it).

**Comment by Snap974** [comment]
I was tried but I still get the same result, 'undefined' :-/

```
var note = new apn.Notification();
  note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
  note.badge = 3;
  note.sound = 'ping.aiff';
  note.alert = message;
  note.payload = {'messageFrom': 'Test'};
  note.clearBadge = true;
  var iosTokensFinish = [];
  listToken.forEach(function (item) {
    iosTokensFinish.push(item.token);
  });
  console.log('BEFORE SEND: ', note.id);
  connection.send(note, iosTokensFinish).then(function (response) {
    console.log('SEND SUCCESS: ', note.id);
    console.log('RESPONSE SUCCESS: ', response);
    response.sent.forEach(function (token) {
      notificationSent(token, note, listToken);
    });
    response.failed.forEach(function (failure) {
      console.log('failed: ', failure);
      if (failure.error) {
        notificationError(failure, failure.error);
      } else {
        notificationFailed(failure, failure.status, failure.response, note);
      }
    });
  });
console.log('AFTER SEND: ', note.id);
```

Here the result:

> BEFORE SEND:  undefined
> AFTER SEND:  undefined
> SEND SUCCESS:  undefined
> RESPONSE SUCCESS:  { sent: [ { device: '55224ba89249b0d95f23b301dcdac8c5de792153befd8291a1d296be5bff345f' } ],
>   failed: [] }

Do you have another idea :) ? 

Thanks

**Comment by jpwilliams** [comment]
The only reference I can find in the code is [here](https://github.com/node-apn/node-apn/blob/master/lib/notification/index.js#L46), where it sets it if you explicitly set an `id` on the notification.

Confirmation from another contributor would be awesome, but I _assume_ that [the docs](https://github.com/node-apn/node-apn/blob/master/doc/notification.markdown#notificationid) mean that `notification.id`, if undefined, is auto-generated on APNS's side (as opposed to within the library before sending).

Your best bet may well be to set IDs yourself using something like [`uuid`](https://www.npmjs.com/package/uuid) to keep track of them.

**Comment by florianreinhart** [comment]
@jpwilliams is correct.

You should set the id to a generated UUID before sending it. If you don't set the id, APNs will generate a UUID, but that UUID is random and probably of no use to you.

I am not sure if APNs actually returns the generated UUID on success. Currently we ignore any response data, when the HTTP status is 200, see [client.js line 73](https://github.com/node-apn/node-apn/blob/master/lib/client.js#L73). However, if an APNs error occurs (i.e. HTTP status code != 200) we return the status code and response body, see [client.js line 83](https://github.com/node-apn/node-apn/blob/master/lib/client.js#L83).

**Comment by Snap974** [comment]
Hi, Thanks for your answers, I will generate a new ID myself;). 

Too bad that APN does not do it internally to track notifications.

Have a nice day.
