### ISSUE TITLE
is it deprecated error event on connection?

### ISSUE THREAD

**Issue by breaklee** [node-apn/node-apn#502]
there were some events
"connected", "disconnected", "completed", "transmitted", "transmissionError",
"cacheTooSmall", "timeout", "Error", "sockerError".
in 1.x version.

is it available  in Provider in v2.x? all event.

**Comment by florianreinhart** [comment]
No, these are not available when using the new HTTP/2 provider API. node-apn 2.* uses callbacks to return errors.
