### ISSUE TITLE
Cannot find ./aes

### ISSUE THREAD

**Issue by pkasson** [node-apn/node-apn#503]
Hi,

While I am new to node, I am able to run the apns js from node directly without issue, sends out notification !

Trying to add the apns module into larger solution and as soon as I add the apns reference, I get this:

Error: Cannot find module './aes'

This is all in the same project / module folder.  Again, running from CLI it works fine, but otherwise, epic fail.

Thanks !

**Comment by florianreinhart** [comment]
No idea what's going on here.

@pkasson Is this still an issue for you?
