### ISSUE TITLE
responses for sent and failed (error)?

### ISSUE THREAD

**Issue by jjb** [node-apn/node-apn#504]
the docs show the response for failed (rejected) as having an http status code. is this the only response type that has this, and is it always 410? it seems odd to include the http status code at this level, and only for this response type.

https://github.com/node-apn/node-apn/blob/master/doc/provider.markdown#sent

**Comment by zaumreit** [comment]
It's just an example and there would be not only 410 but all the [status code](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW15) defined by APNs.

**Comment by jjb** [comment]
@zaumreit thanks. would the status code be included in the error state as well, or only in the rejected state?

if the values are just strings in the success state, and the status key is only present in the rejected state, then checking for state is pretty awkward. also it makes me insecure about the api not changing, maybe status will start to be included in the error state. here's how i'm checking for the state of the response (in coffeescript).

```coffeescript
@client.send(note, deviceToken).then (result) => 
  for device in result
    if typeof device == "string"
      console.log "success"
    else if "status" of device # coffeescript's weird operator for checking hash key presence
      console.log "failed - rejected"
    else
      console.log "failed - error"
```

This is the only way to do it, right?

**Comment by jjb** [comment]
to further add to the confusion, it looks like what is returned is completely different :) or maybe i'm reading the docs incorrectly


```json
{
  "sent":[],
  "failed": [
    {"device":"an-apns-token","status":"400","response":{"reason":"BadDeviceToken"}}
  ]
}
```

**Comment by zaumreit** [comment]
@jjb You're right and I commented on #480 PR for the same concerns.

**Comment by jjb** [comment]
🆒

**Comment by florianreinhart** [comment]
Sending a notification can fail for two reasons:

1. The notification is rejected by APNs (or any other error occurs on APNs' side). APNs will return an appropriate HTTP status code, e.g. 410. When this happens node-apn will return the status code to the client.
2. The connection to APNs fails, e.g. network is down. When this happens node-apn will return an error object to the client.
