### ISSUE TITLE
Push notification fails with reason  'BadDeviceToken'.

### ISSUE THREAD

**Issue by asif13** [node-apn/node-apn#506]
Below is the code I am using 
apnProvider.send(notification, deviceToken).then(function(result) {  
    console.log(result);
    console.log(result['failed']);
});

**Comment by zerbfra** [comment]
This is a know issue, see pull request #480

**Comment by asif13** [comment]
@zerbfra so is there any way I can workaround it ? Because I am following the docs and still seeing this error ?

**Comment by zerbfra** [comment]
We are waiting the pull request to be merged.
if you need it now you can always do this locally

**Comment by asif13** [comment]
to do it locally,I will have to replicate the changes from #480 ?

**Comment by zerbfra** [comment]
yep, it should work

**Comment by hools** [comment]
any good news / resolution on this? My server works perfectly in dev mode but I get 'bad token' in prod mode (and yes I am sending the proper prod device token). thx

**Comment by debjeet-sarkar** [comment]
@hools Have you tested the certificates with openssl ? If not try :

openssl s_client -connect gateway.push.apple.com:2195 -cert cert.pem -key key.pem # production

It should work . Might be an issue with the code signing on the client side as well, Is the target device token received after signing the code with the proper code signing certs for which you have the certificates prepared on your server side.

Any mismatch in the env will return you error 8.

**Comment by hools** [comment]
@debjeet-sarkar thanks for the suggestions. I am using apn token auth which is same for dev & prod. However, it's working again. I think it was a build issue on xcode...although I was building for 'release', for some reason iOS was not giving me a device token valid for prod; it only works when installed via testflight, and not directly into device (in which case it's a sandbox device token always). 
ps: still think we should get #480 finished up and deployed though
cheers!

**Comment by debjeet-sarkar** [comment]
@hools , cool and yeah, this shall solve the IDLE_TIMEOUTS that we face often.

**Comment by hools** [comment]
yes. but of course now I'm also suffering from idle timeouts and 500 errors (issue #449)

=(

**Comment by remirobert** [comment]
same issue : BadDeviceToken

**Comment by debjeet-sarkar** [comment]
@remirobert  Is the profile with which you are signing the app the correct one ? Is the certificate residing on the server side of the same env for which the app is being built ? This issue generally occurs if there is a discrepancy between these two credentials.

**Comment by zerbfra** [comment]
This should be fixed now -  the pull request has been merged

**Comment by remirobert** [comment]
awesome !! 🎉 Let's get notification push back !

**Comment by debjeet-sarkar** [comment]
Can this issue be closed if its resolved ?

**Comment by florianreinhart** [comment]
I am closing this issue. If you still have any issues, feel free to reply.

**Comment by mariohmol** [comment]
Hi there.. i'm having this issue with version 2.1.4 . should i use a specific version to have this fix?

**Comment by bugfreetech** [comment]
something i've noticed, you can get this error if trying to push to a dev ID from a production environment & vice versa. Apple have recently updated how they deal out certificates & it's much easier now.

**Comment by debjeet-sarkar** [comment]
@bugfreetech , correctly said. @mariohmol try : 

openssl s_client -connect gateway.push.apple.com:2195 -cert cert.pem -key key.pem # production

Just to be sure that the certificates generated are valid for prod.

**Comment by ammadakhtar** [comment]
i am still having this issue

**Comment by oliversalzburg** [comment]
@ammadakhtar I think you're supposed to provide more details with your reply. This information doesn't help anyone.

**Comment by ammadakhtar** [comment]
@oliversalzburg 
using node version 8.0.0
and when i run my app.js i get this in terminal 
{"sent":[],"failed":[{"device":"mytoken","status":"400","response":{"reason":"BadDeviceToken"}}]}

**Comment by docpllana** [comment]
For me this made the error go away:

1) Delete your app in your iPhone that you have installed through Xcode

2) Product > Archive > Export > Save for Ad Hoc Deployment > upload to:
https://www.diawi.com/

3) Download & Install application from diawi download URL.

4) New device id key generated, use it to send notification from Production server.

Most important is to delete the old app installed with Xcode, that produce the development device key.

Installing new app from diawi will install your app with production device key and you can use production url.
Production URL: https://api.push.apple.com/3/device/123456. (12345 is ex. of device id)

**Comment by MuhammadHamzaRajput** [comment]
make sure you are using debug mode token in non production environment i.e production = false 
and using release mode token in production environment i.e production = true.
Because production token is not working in non production enviroment.

**Comment by alvaro1728** [comment]
@MuhammadHamzaRajput What does that mean?  "i.e production = true" where do you set this?  Please be more specific.  Thanks.

**Comment by WestFlow127** [comment]
My device token looks like this from the iOS didReceiveRegistrationToken function: 
> ddoY6uUwWkmZiPstP1T_Ng:APA91bG_gl2rhdAckwocRMwcnEIVnOw....EFsQNOjPjiXzEIEOkZG4oYCe2ITNDvNUxPRTWCAA9UgxMlUGjJo9q2EV7NkOfKGdR6Rs3hp6_jTkzZlGSKlN31dk6NhUR7

How do I convert this to a hex encoded string to use in the apnProvider.send() function?

**Comment by iamromec** [comment]
@WestFlow127 If you're getting it from a plug-in, use it like this.fm.getToken('apns-string');
