### ISSUE TITLE
Node 4.6.0 fails

### ISSUE THREAD

**Issue by mihai-iorga** [node-apn/node-apn#512]
As documentation:
[`Buffer.from was introduced in version 6.0.0`](https://nodejs.org/docs/v6.0.0/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe)
`To make the creation of Buffer objects more reliable and less error prone, the various forms of the new Buffer() constructor have been deprecated and replaced by separate Buffer.from(), Buffer.alloc(), and Buffer.allocUnsafe() methods.`

This commit: [#6c9118e](https://github.com/node-apn/node-apn/commit/6c9118e) says that you need at least 4.6.0 but `Buffer.from()` does not exist in 4.6.0.

This commit: [#fac48d9](https://github.com/node-apn/node-apn/commit/fac48d9) breaks everything if you do not update Node to at least 6.0.0

Actual error:

    TypeError: this is not a typed array.
        at Function.from (native)
        at Object.<anonymous> (/server/current/node_modules/apn/lib/protocol/endpoint.js:17:31)

**Comment by florianreinhart** [comment]
Node.js documentation says, it was introduced in 4.5.0, see https://nodejs.org/docs/v4.6.0/api/buffer.html#buffer_class_method_buffer_from_str_encoding

We have 100% test coverage and all tests pass on the latest version auf node 4, 5, 6 and 7.

**Comment by mihai-iorga** [comment]
Latest version does not mean everyone has the latest version of any Major version ...

**Comment by oliversalzburg** [comment]
@florianreinhart Maybe you're interested in following this ticket: https://github.com/nodejs/node/issues/10825
