### ISSUE TITLE
Error 400 : MissingTopic

### ISSUE THREAD

**Issue by remirobert** [node-apn/node-apn#514]
I got an error when sending notification push with cert.pem, and key.pem.

```javascript
let apn = new apn.Provider({
  cert: "./conf/cert.pem",
  key: "./conf/key.pem",
  passphrase: "remi"
});
```

Error:
```
[
{ device: '00d27bf6986d4567ced11fdc32dfce0cc10878bba888659bc965b530ad473dbc',
status: '400',
response: { reason: 'MissingTopic' } } 
]
```

**Comment by eiosca** [comment]
Hi, do you have check [this](https://github.com/node-apn/node-apn/wiki/Preparing-Certificates) ?

Open with text editor you cert.pem, for me the cert and key was in the same file.

**Comment by oliversalzburg** [comment]
You don't really need the topic with certificate-based auth. This is a useless error message produced by the APNS sandbox.

You can add a `topic` member to your payload to resolve the error, but then APNS will complain in production because it is invalid to supply a `topic` with certificate-based auth.

**Comment by eiosca** [comment]
@oliversalzburg Of course you're right, i'm stupid :(

**Comment by remirobert** [comment]
@oliversalzburg How to add the topic in the payload ?
I want to use it in prod. And it was working fine in development.
Thanks.

**Comment by oliversalzburg** [comment]
@remirobert An example containing the topic is given at https://github.com/node-apn/node-apn#sending-a-notification

If you're adding it, don't be surprised if you (or another dev on your team) is going to remove it soon after ;P

**Comment by remirobert** [comment]
@oliversalzburg thank you.
