### ISSUE TITLE
Transmission error 8

### ISSUE THREAD

**Issue by harshalyeole-tudip** [node-apn/node-apn#515]
I am using production certificate files (key.pem & cert.epm) even though I'm facing same issue.
Please help me out on this.

Transmission Error 8 
{ encoding: 'utf8',
  payload: 
   { aps: 
      { badge: undefined,
        sound: undefined,
        alert: 'hiiiii',
        'url-args': undefined,
        category: undefined } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"aps":{"alert":"hiiiii"}}',
  truncateAtWordEnd: false,
  _alert: 'hiiiii' } Device {
  token: <Buffer 22 bc ee d5 fb 89 df 0c d4 fd 02 8c 03 0e 32 12 20 60 c2 3d 37 40 51 98 d8 37 c2 c2 59 ce f4 ab> }
Status: Transmission Error 8 { encoding: 'utf8',
  payload: 
   { aps: 
      { badge: undefined,
        sound: undefined,
        alert: 'hiiiii',
        'url-args': undefined,
        category: undefined } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"aps":{"alert":"hiiiii"}}',
  truncateAtWordEnd: false,
  _alert: 'hiiiii' } Device {
  token: <Buffer 22 bc ee d5 fb 89 df 0c d4 fd 02 8c 03 0e 32 12 20 60 c2 3d 37 40 51 98 d8 37 c2 c2 59 ce f4 ab> }
Status: Transmitted
Status: Transmitted
Status: Transmission Error 8 { encoding: 'utf8',
  payload: 
   { aps: 
      { badge: undefined,
        sound: undefined,
        alert: 'hiiiii',
        'url-args': undefined,
        category: undefined } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"aps":{"alert":"hiiiii"}}',
  truncateAtWordEnd: false,
  _alert: 'hiiiii' } Device {
  token: <Buffer 22 bc ee d5 fb 89 df 0c d4 fd 02 8c 03 0e 32 12 20 60 c2 3d 37 40 51 98 d8 37 c2 c2 59 ce f4 ab> }

**Comment by eiosca** [comment]
Hi, do you check this #184 ?

Are you sure about the options of Apn Provider:
`production: `

**Comment by harshalyeole-tudip** [comment]
It's solved it was Apple build issue.
Thank you.
