### ISSUE TITLE
TopicDisallowed

### ISSUE THREAD

**Issue by j4nos** [node-apn/node-apn#517]
Why does server receive 'TopicDisallowed' error? Is it possible to use one provider token for two different Bundle ID, belong to the same account / team? 

Server sends push notification to APNS but for second Bundle ID receives error:

    status: '400',
    response: { reason: 'TopicDisallowed' } } ]

Any idea what is wrong? Using the code in both script file.

**Comment by oliversalzburg** [comment]
Possibly relevant: #514

**Comment by florianreinhart** [comment]
@j4nos Is this still an issue for you?

**Comment by j4nos** [comment]
Nope
