### ISSUE TITLE
One Provider per-process for each certificate using pm2

### ISSUE THREAD

**Issue by ekhmoi** [node-apn/node-apn#520]
Hello. 
It is mentioned in documentation that 

> You should only create one Provider per-process for each certificate/key pair you have. You do not need to create a new Provider for each notification. If you are only sending notifications to one app then there is no need for more than one Provider.

i run my application using pm2 -i max
which starts multiple instances of my application therefore multiple Providers are generated.
the question is: is it normal? will i get some errors  or unexpected behaviour ?

**Comment by florianreinhart** [comment]
You should not create more than one provider per process for each certificate. So, you should be fine.
