### ISSUE TITLE
Show notification even when inside application

### ISSUE THREAD

**Issue by AmitMY** [node-apn/node-apn#530]
When I send a notification and the user is outside the app, it shows a normal notification.
However, If I send a notification while the user is inside the app, the app automatically processes the notification as if it was pressed, and no notification is shown.

Am I missing a config parameter or something that can disable this behavior?

**Comment by oliversalzburg** [comment]
This is nothing you control by changing the configuration of node-apn.

**Comment by AmitMY** [comment]
Thanks @oliversalzburg , Do you by any chance know how can I disable that behavior?

**Comment by oliversalzburg** [comment]
You will have to register your own handler: https://developer.apple.com/reference/uikit/uiapplicationdelegate/1623117-application?language=objc

This handler is *only* called if your app is running, otherwise the notification is purely handled by the OS. When you receive the notification, you can either show custom content or schedule a local notification for the same content.

**Comment by florianreinhart** [comment]
iOS 10 added an option to display the system UI for a notification while your app is running: https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter

Before iOS 10 you had to manually display an alert or some other UI in your app.

@oliversalzburg I am not sure how scheduling a local notification would help in here.

**Comment by AmitMY** [comment]
Thanks @florianreinhart 
A tiny bit irrelevant to me, as I am using a web application, but helpful nonetheless.

**Comment by oliversalzburg** [comment]
I thought the local notification is displayed to the user like a remote notification would when outside the app.

I'm really more of a backend guy here. So, sorry if the approach didn't make any sense :P In that case I'm also interested to learn how to achieve this :D

**Comment by florianreinhart** [comment]
I don't have any experience with web apps.

For an iOS app it depends on your deployment target. In iOS 10 and up there is an API in the new User Notifications framework, see https://developer.apple.com/reference/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter

For iOS 9 and earlier you basically have to roll your own. The simplest solution would be to display an alert in your app from the UIApplicationDelegate method.
