### ISSUE TITLE
Notification is sent but never delivered to the device...

### ISSUE THREAD

**Issue by tunds** [node-apn/node-apn#532]
So i've followed the documentation to send a notification and it seems to give me a success in the logs since the result of the closure is this.

```
{
"result": {
"sent": [
{
"device": "xxxxxxxxxxxxx"
}
],
"failed": []
}
}
```

The only issue is that the notification is never actually delivered to the device although i'm recivieing a 200 response of success below is the code i'm using to send the notification.

```
    var options = {
        token: {
            key: __dirname + "/public/key.p8",
            keyId: "xxxx",
            teamId: "xxxxx"
        },
        production: false
    };

    var apnProvider = new apn.Provider(options);

    var notification = new apn.Notification();


    notification.rawPayload = {
        sound : "Wakeup.wav",
        aps: {
            alert: {
                title : "Good morning!",
                subtitle: "Today's forcast in ",
                body: ""
            },
            "mutable-content" : 1,
            icon: "cloudy"
        }
    };

    notification.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
    notification.topic = "tunds.myapp";

    apnProvider.send(notification, "xxxxxxx").then(function (result) {
        response.success(result);
    });
    
```

**Comment by tunds** [comment]
Update I've tested if my application is set up properly to receive notifications on iOS and everything works when pushing a notification with a apns testing tool which is why i reopened the ticket since the issue is still persisting.

**Comment by mihai-iorga** [comment]
I don't think setting the rawPayload does anything ... It does not set anything:

```
var notification = new apn.Notification();
notification.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
notification.topic = "tunds.myapp";
notification.alert = "Good morning!";
apnProvider.send(notification, "xxxxxxx").then(function (result) {
    response.success(result);
});
```

**Comment by tunds** [comment]
@mihai-iorga The actual issue was that the device token didn't exist on that device anymore, which makes me wonder why was it giving me a success rather than a 410 error?

**Comment by tunds** [comment]
I've resolved this issue it's weird behaviour with iOS in sandbox mode if anyone else has the same issue follow these steps http://stackoverflow.com/questions/37410227/how-to-test-apple-push-notifications-feedback-service/39318941#39318941
