### ISSUE TITLE
APN callback

### ISSUE THREAD

**Issue by rohitipredictt** [node-apn/node-apn#533]
Hi how can i get callback from my apn function , so that i can forward it to my APIs.
I am just a newbie to javascript, when i an using callback()  The respose is callback() is not a function.

function sendiosNotification(notification,callback){
        

        if(!notification.data.to){
            return callback({error : false, message : "receiver's deviceid is not available. could not send notificaion"});
        }
        var client = new apns.Provider({
            cert:"./cert/cert.pem",
            key:"./cert/key.pem",
            production: true,

        });
        var notifi = new apns.Notification();
        notifi.topic = "---"
        notifi.alert = notification.data.message;
        notifi.title = notification.data.username;
        device_token = notification.data.to;     
        client.send(notifi,device_token).then(result =>{
            console.log(result);
            callback()
        });
    }

data is coming from my api. I can succssfully send notifications to my devices but the function is not sending any response back.

sendiosNotification({ data : data })

**Comment by mihai-iorga** [comment]
I think you should start to study more in what is a [callback](https://docs.nodejitsu.com/articles/getting-started/control-flow/what-are-callbacks/), a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) and how to chain them.

**Comment by rohitipredictt** [comment]
I just want to know how apn provide a response

**Comment by mihai-iorga** [comment]
Same as all NodeJS components. Callback or Promise. If you do not understand how those work you will have a hard time with any javascript module.
