### ISSUE TITLE
Support for Safari notifications (Desktop)

### ISSUE THREAD

**Issue by callmeahab** [node-apn/node-apn#534]
Does node-apn support sending safari push notifications, and in that case can I get an example of how the setup is done?

P.S. Thanks for the great work on node-apn...

**Comment by silentjohnny** [comment]
You can use the APN Auth Key for anything that needs to be sent over APNS, as long as it belongs to your Team Identifier. The service you wanna target (iOS Development, iOS Production, Passbook or Safari Push) defines which topic you need to attach to the Notification.

So, for Safari Push, the topic would be something like web.com.example.test, for passbook updates it would be something like pass.com.example.test and for iOS push it would be somehing like com.example.test:

```javascript

const apn = require('apn'),
    fs = require('fs');

const provider = new apn.Provider({
    token: {
        key: fs.readFileSync('APNAuthKey_XYZ456.p8'),
        keyId: 'XYZ456',
        teamId: 'ABCD1234'
    }
});
const notification = {
    alert: ....,
    topic: 'web.com.example.test'
};
provider.send(notification, deviceToken).then((response) => {
    // handle 
});

```

As for the generation of the push package, that is outside of the scope of this module.

**Comment by callmeahab** [comment]
@silentjohnny thanks for your answer.

Can you just tell me if its possible to sign push package using token, since apple documentation  only mentions signing it with certificate: https://developer.apple.com/library/prerelease/content/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html

**Comment by silentjohnny** [comment]
No, Push Packages (and PKPass, for that matter) can only be signed with a certificate, since the browser needs to be able to verify it. The APN Auth Key can only be used to sign a JWT for authenticating to APNS.

**Comment by callmeahab** [comment]
Ok, thanks for clarifying.

**Comment by mfbx9da4** [comment]
How do you generate the p8? Right now I only have a p12.
