### ISSUE TITLE
How to I can Increase APN  Expiry time one week set? 

### ISSUE THREAD

**Issue by rajkuttie** [node-apn/node-apn#540]
Already Documentation gave one hr().But I want set time at one week. I'm try to apply many javascript functions (one week= `note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now. `    ). But I had error for "bad expiration".  How I can set one week.

**Comment by mihai-iorga** [comment]
3600 are seconds (60 seconds * 60 minutes = 3600 seconds = 1 hour). You can set to 
`note.expiry = Math.floor(Date.now() / 1000) + (60 * 60 * 24 * 7);` (60 seconds * 60 minutes * 24 hours * 7 days)

APNS Expiration: A UNIX epoch date expressed in seconds (UTC). This header identifies the date when the notification is no longer valid and can be discarded.
If this value is nonzero, APNs stores the notification and tries to deliver it at least once, repeating the attempt as needed if it is unable to deliver the notification the first time. If the value is 0, APNs treats the notification as if it expires immediately and does not store the notification or attempt to redeliver it.

In 2009 [PC World](http://www.pcworld.com/article/167652/the_limits_of_apples_push_notification_for_the_iphone.html) stated that max expiration is 28 days ... but the [documentation](https://developer.apple.com/library/prerelease/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html) does not say anything about this.

**Comment by rajkuttie** [comment]
@mihai-iorga  Thanks man.. !  I get it more info ..
