### ISSUE TITLE
Document `apn.Provider.shutdown()` in README

### ISSUE THREAD

**Issue by eladnava** [node-apn/node-apn#542]
Hi everyone,
First off, thanks so much for your hard work on this project!

I deployed `apn` to a production system that creates a lot of `apn.Provider` objects, one per customer. What I later noticed is that Node.js would be killed due to consuming 95% of the available system memory.

After some investigation, I figured out that this leak was being caused by `apn`. As soon as I sent 300 notifications via 300 different `aps.Provider` objects, memory usage soared and did not decrease after notifications had already been sent via the provider objects.

I then realized that there is probably some way to shut down the provider to release its resources (I wasn't aware it had any) and was able to find this documented in the [doc/provider.markdown](https://github.com/node-apn/node-apn/blob/master/doc/provider.markdown) file.  

This is great but I think it could be better if we also document the need to shut down providers which are no longer needed in the main `README.md`. Otherwise, the current code section in README.md leaks, which is not too bad for one provider but some people like myself might be creating lots of providers which over time causes mass destruction.

I was thinking of adding it next to this existing section: 

> You should only create one `Provider` per-process for each certificate/key pair you have. You do not need to create a new `Provider` for each notification. If you are only sending notifications to one app then there is no need for more than one `Provider`.

What do you think? Can I submit the PR?

**Comment by florianreinhart** [comment]
@eladnava Please create a pull request and we can discuss your changes.

**Comment by eladnava** [comment]
@florianreinhart #542, thanks!
