### ISSUE TITLE
SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by rajkuttie** [node-apn/node-apn#548]
Already I am developed Push notification.  Then We are plan to move another Development setup.  Now I got this Issues. 

` apnProvider.send(note, deviceToken).then( (result) => {
-bash: syntax error near unexpected token `note,'
`

![capture](https://cloud.githubusercontent.com/assets/5540988/24183279/6d6d7746-0eed-11e7-90b0-09f347ca4524.PNG)

**Comment by DJHoltkamp** [comment]
Looks like you are using too old of version of Javascript to use an that ES6 feature. If you make that function(result) {}   vs (result)=> {}) it should get past this issue. You may still have issues with this library without modification if you are using this old of version of node though.

**Comment by rajkuttie** [comment]
@DJHoltkamp  Yeah. Thanks. After I update my node. I solved this problem .
