### ISSUE TITLE
What does this error mean? -> Failed to generate token: Could not find expected "seq"

### ISSUE THREAD

**Issue by tobiasmuecksch** [node-apn/node-apn#552]
Hey there,

I can't find out what this error means. Googling around does not provide any helpful information.

What does this error mean?
```
/Users/tmuecksch/Sites/microservices/microservice-notification/node_modules/apn/lib/credentials/token/prepare.js:45
      throw new VError(err, "Failed to generate token");
      ^
VError: Failed to generate token: Could not find expected "seq"
    at prepareToken (/Users/tmuecksch/Sites/microservices/microservice-notification/node_modules/apn/lib/credentials/token/prepare.js:45:13)
    at config (/Users/tmuecksch/Sites/microservices/microservice-notification/node_modules/apn/lib/config.js:42:31)
    at new Client (/Users/tmuecksch/Sites/microservices/microservice-notification/node_modules/apn/lib/client.js:11:19)
    at Provider (/Users/tmuecksch/Sites/microservices/microservice-notification/node_modules/apn/lib/provider.js:12:19)
    at Object.<anonymous> (/Users/tmuecksch/Sites/microservices/microservice-notification/test/apnProviderTest.js:14:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

**Comment by ParulShukla90** [comment]
Hi,
I am getting the same error. Any help would be appreciated.

**Comment by tobiasmuecksch** [comment]
What are you using as key? A .p12 oder .p8 file?

The error disappeared for me when I changed to a .p8 file.
I haven't tested sending a notification yet - but establishing the connection to APN seems to work with that.

**Comment by ParulShukla90** [comment]
Hi @tobiasmuecksch ,

Thanks for the quick response. I am not using P8 file let me try with P8 file.

**Comment by ParulShukla90** [comment]
@tobiasmuecksch ,
Thank you it works perfectly.

**Comment by OKNoah** [comment]
@tobiasmuecksch I don't see an option for `.p8`. I am following this guide: https://github.com/node-apn/node-apn/wiki/Preparing-Certificates

**Comment by tobiasmuecksch** [comment]
@OKNoah is that a question or a statement?

**Comment by Balasnest** [comment]
I could able to export in p12. But How will I get the p8 file ?

**Comment by arolando** [comment]
Samer error here, I followed the guide at https://github.com/node-apn/node-apn/wiki/Preparing-Certificates. Did any of you resolved?

**Comment by oliversalzburg** [comment]
> Did any of you resolved?

Yes, they did and they posted about it in this thread.

**Comment by zhouhao27** [comment]
@oliversalzburg Where? I got this error when I'm using pem. Can I use p12 because I don't have access to generate the p8 file.

**Comment by roysG** [comment]
any update?

**Comment by Thomas0c** [comment]
I was getting a similar error, but ended digging up old documentation to see how it used to work.

I was getting the error when I used the following formatting:
```
const apnOptions = {
    token: {
      key: "path/to/key.pem",
      keyId: "key-id",
      teamId: "developer-team-id"
    },
    production: false
};
```

It seems that `.pem` files and the `token` object are not supposed to be used together. Rather the provider object should have `key` and `cert` specified - see sample below:

```
const apnOptions = {
    key: "public/key.pem", (.p12 file converted to .pem)
    cert: "public/cert.pem",
    production: false
};
```

**Comment by Mtanash** [comment]
Any updates on this issue with .p8 ?
