### ISSUE TITLE
VError: socket hang up & ECONNRESET

### ISSUE THREAD

**Issue by magicdawn** [node-apn/node-apn#562]
with token based provider.

- the following image is on top of apn@latest = @2.1.4, and no success push delivered
- on apn@2.1.1 gets `InvalidProviderToken` response from Apple

<img width="725" alt="qq20170427-150905 2x" src="https://cloud.githubusercontent.com/assets/4067115/25471926/c46a1600-2b5b-11e7-8281-55dc236e7695.png">

**Comment by florianreinhart** [comment]
@magicdawn are you still facing this issue?

`InvalidPushToken` is exactly what it sounds like, you are using an invalid token. This can also happen if you use development token, but try to send the push notification through the production APNs, or vice versa.

**Comment by florianreinhart** [comment]
I am closing this. Please let us know if you are still facing this issue.
