### ISSUE TITLE
Sending custom messages per token (API usage question)

### ISSUE THREAD

**Issue by ded** [node-apn/node-apn#564]
Heyo,
We've been using `node-apn` in production for the last year for [agent.com](https://agent.com), and I'm looking to customize our notifications per user when sending batches of tokens.

I'm currently taking advantage of the `array` of tokens that can be passed to `provider.send(note, ['a', 'b', 'c', 'd', 'e', 'f', ...])`, but the drawback is that it requires each user is sent the same message in the `note`.

Instead it would be great if I can say `['Hi Jessica, ...', 'Hi Sarah, ...', 'Hi Ashley, ...']`... which I can achieve, but only if I send a bunch of individual calls to `send`.

What do you recommend?

**Comment by florianreinhart** [comment]
It basically comes down to what you suggest. You have to send each message individually.

Even if node-apn would have an option to provide a template message and customize it for each token, it would have to create a separate message for each token in the end anyways.

**Comment by ded** [comment]
@florianreinhart cool, just thought i'd ask 👍  there was no problem at all adding a wrapper. cheers 😃
