### ISSUE TITLE
'BadDeviceToken' 

### ISSUE THREAD

**Issue by davidkr** [node-apn/node-apn#568]
Hi,
apn version 3.10.10  ( What I get after npm install apn ) 
Running Your Git Example with my values and getting 
Sending: {"aps":{"alert":"Breaking News: I just sent my first Push Notification"}} to <c63963fd fdafa1b9 19f17d8a aea9c3bf 40ce64c9 9f34fd5e 9b878151 37461e47>
sent: 0
failed: 1
[ { device: '<c63963fd fdafa1b9 19f17d8a aea9c3bf 40ce64c9 9f34fd5e 9b878151 37461e47>',
    status: '400',
    response: { reason: 'BadDeviceToken' } } ]

From Xcode - the generated device token string is : c63963fdfdafa1b919f17d8aaea9c3bf40ce64c99f34fd5e9b87815137461e47

And the code I run is basically your example - 
"use strict";

/**
Send an identical notification to multiple devices.
Possible use cases:
 - Breaking news
 - Announcements
 - Sport results
*/

const apn = require("apn");

let tokens = ["<c63963fd fdafa1b9 19f17d8a aea9c3bf 40ce64c9 9f34fd5e 9b878151 37461e47>"];
                
let service = new apn.Provider({
  cert: "/Users/davidkramf/documents/cert/cert.pem",
  key: "/Users/davidkramf/documents/cert/key.pem",
});

let note = new apn.Notification({
	alert:  "Breaking News: I just sent my first Push Notification",
});

// The topic is usually the bundle identifier of your application.
note.topic = "<com.hirhur.stam1>";

console.log(`Sending: ${note.compile()} to ${tokens}`);
service.send(note, tokens).then( result => {
    console.log("sent:", result.sent.length);
    console.log("failed:", result.failed.length);
    console.log(result.failed);
});

// For one-shot notification tasks you may wish to shutdown the connection
// after everything is sent, but only call shutdown if you need your
// application to terminate.
service.shutdown();
Many Thanks, David

**Comment by davidkr** [comment]
I never know if to take these brackets seriously ... Case closed.

**Comment by MuhammadHamzaRajput** [comment]
where are you show is this mode is development or production?
