### ISSUE TITLE
Augment .gitignore with version for the .gitignore project

### ISSUE THREAD

**Issue by jkwuc89** [node-apn/node-apn#572]
[github/gitignore](https://github.com/github/gitignore) contains a set of well-maintained .gitignore templates for all sorts of projects, including Node.js. I recommend augmenting .gitignore inside this project using the Node.js template from github/gitignore. I also recommend adding common ignore directives for IDEs and editors.

**Comment by florianreinhart** [comment]
Can you submit a PR for this? That would be great!

**Comment by jkwuc89** [comment]
Will do for this issue and for the .nvmrc issue.

**Comment by florianreinhart** [comment]
Fixed by #573
