### ISSUE TITLE
Notification can't sent - Reason : Unregistered , Status Code: 410 

### ISSUE THREAD

**Issue by rajkuttie** [node-apn/node-apn#574]
My response : 

![screen shot 2017-06-02 at 2 17 19 pm](https://cloud.githubusercontent.com/assets/5540988/26718604/2f42e15a-479f-11e7-9fd6-12b840d920b5.png)

**Comment by wong2** [comment]
maybe the user has uninstalled your app

**Comment by florianreinhart** [comment]
I am closing this. Please let us know if you are still facing this issue.
