### ISSUE TITLE
Error installing apn

### ISSUE THREAD

**Issue by shrutiWV** [node-apn/node-apn#575]
\node-apn-master>npm install apn
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "apn" under a package
npm ERR! also called "apn". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wv117\AppData\Roaming\npm-cache\_logs\2017-06-19T12_15_01_569Z-debug.log

**Comment by florianreinhart** [comment]
I am closing this. This is not related to node-apn.

**Comment by shrutiWV** [comment]
Than can you please explain me what is the actual issue why i can't able to
install apn??

[image: photo]

*Thanks and Regards*
*Shruti Raikwar*
*Webvillee Technologies Indore*
*Contact No- 9977030410 *
