### ISSUE TITLE
.p8 file error, VError: Failed loading token key: EACCES: permission denied, open '/root/app/file.p8

### ISSUE THREAD

**Issue by hendralimmm** [node-apn/node-apn#576]
so i use this package for apple push notif, it's working nicely in my staging server / development server,
but somehow, when i deploy my application to my production server which hosted in AWS, using ubuntu 14.04,
when i tried to trigger push notif, i got this error :

```
VError: Failed loading token key: EACCES: permission denied, open '/root/app/file.p8'
 at prepareToken (/home/ubuntu/app/web/node_modules/apn/lib/credentials/token/prepare.js:15:13)
 at config (/home/ubuntu/app/web/node_modules/apn/lib/config.js:42:31)
 at new Client (/home/ubuntu/app/web/node_modules/apn/lib/client.js:11:19)
 at EventEmitter.Provider (/home/ubuntu/app/web/node_modules/apn/lib/provider.js:12:19)

```

i have tried to change .p8 file permition with chmod, tried 0400, 0777 without any luck.
i also tried to change my app folder owner with chown to ubuntu

but nothing works, please help, i am stuck.

**Comment by florianreinhart** [comment]
Looks like your app is running as the `ubuntu` user, but you try to access a file from `root`. Why don't you place the .p8 file in the same folder as your code?

**Comment by hendralimmm** [comment]
@florianreinhart thank you for your response, ok about my .p8 file actually it's in the same folder with my code, this is the actual path to p8 file "/home/ubuntu/app/web/src/server/lib/file.p8" i thought that it would be simpler to explain, so i change it to "/root/app/file.p8".

is we host our application in AWS ubuntu, by default ubuntu is the root user, so i can access my file.p8 like this : 

> vim app/web/src/server/lib/file.p8

so in my code that trigger push notification i called it like this : 

```
 token: {
         //   key: '/root/app/web/src/server/lib/file.p8', // Path to the key p8 file,
            keyId: Const.ApnKeyId,
            teamId: Const.TeamId,
        },

```

but as u pointed it out, it looks like my application running as ubuntu, and can not access file as root,
so i changed my key path to this : 

>             key: "/home/ubuntu/app/web/src/server/lib/file.p8"


i think, that did the trick.. thanks for pointed it out!
