### ISSUE TITLE
Crash app When push notification (centos7, node v6.10.3)

### ISSUE THREAD

**Issue by Tan-nn** [node-apn/node-apn#579]
It works fine in local env (macOs Serria) , but the crash in my server. Please help me resolve!

 below my server info:
  Node v6.10.3
 
  Operating System: CentOS Linux 7 (Core)
  CPE OS Name: cpe:/o:centos:centos:7
  Kernel : Linux 3.10.0-327.36.3.el7.x86_64
  Architecture: x86-64

Exception detail:
> /lib64/libpthread.so.0(+0xf370)[0x7f4e394fd370]
> /lib64/libcrypto.so.10(i2c_ASN1_INTEGER+0x70)[0x7f4e3c3edb50]
> /lib64/libcrypto.so.10(asn1_ex_i2c+0x139)[0x7f4e3c3f8579]
> /lib64/libcrypto.so.10(+0x10769a)[0x7f4e3c3f869a]
> /lib64/libcrypto.so.10(ASN1_item_ex_i2d+0x20e)[0x7f4e3c3f89ae]
> /lib64/libcrypto.so.10(+0x107e97)[0x7f4e3c3f8e97]
> /lib64/libcrypto.so.10(ASN1_item_ex_i2d+0x35b)[0x7f4e3c3f8afb]
> /lib64/libcrypto.so.10(+0x107d21)[0x7f4e3c3f8d21]
> /lib64/libcrypto.so.10(ASN1_item_ex_i2d+0x35b)[0x7f4e3c3f8afb]
> /lib64/libcrypto.so.10(+0x107bff)[0x7f4e3c3f8bff]
> /lib64/libssl.so.10(+0x2d95d)[0x7f4e3c0b095d]
> /lib64/libssl.so.10(ssl3_output_cert_chain+0xc3)[0x7f4e3c0b1033]
> /lib64/libssl.so.10(ssl3_send_client_certificate+0xba)[0x7f4e3c0aa43a]
> /lib64/libssl.so.10(ssl3_connect+0x497)[0x7f4e3c0aaa07]
> /lib64/libssl.so.10(ssl23_connect+0x81e)[0x7f4e3c0b3d8e]
> /lib64/libssl.so.10(ssl23_write+0x32)[0x7f4e3c0b47e2]
> /usr/bin/node(_ZN4node7TLSWrap7ClearInEv+0x88)[0xe6f818]
> /usr/bin/node(_ZN4node7TLSWrap6DoReadElPK8uv_buf_t14uv_handle_type+0xbb)[0xe701fb]
> /usr/bin/node(_ZN4node10StreamWrap12OnReadCommonEP11uv_stream_slPK8uv_buf_t14uv_handle_type+0x85)[0xe3a615]
> /lib64/libuv.so.1(+0x15d74)[0x7f4e3c6f0d74]
> /lib64/libuv.so.1(+0x166ac)[0x7f4e3c6f16ac]
> /lib64/libuv.so.1(uv__io_poll+0x368)[0x7f4e3c6f62e8]
> /lib64/libuv.so.1(uv_run+0x128)[0x7f4e3c6e7db8]
> /usr/bin/node(_ZN4node5StartEiPPc+0x3e8)[0xdf9c18]
> /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f4e3914eb35]
> /usr/bin/node[0x6f8a39]

**Comment by amritsinghbains** [comment]
did you find an answer to this?

**Comment by florianreinhart** [comment]
@Tan-non is this still an issue for you? Looks like an issue with OpenSSL.
