### ISSUE TITLE
quotes in keyname mutable-content

### ISSUE THREAD

**Issue by sirajabbas** [node-apn/node-apn#584]
Hi ,
I have a problem while using this module.The notification JSON contains single quotes in key mutable-content.
Plz see the screenshot
![qutoes issue](https://user-images.githubusercontent.com/9496103/28264994-35069f5c-6b0b-11e7-8810-93a9bba8cbf8.jpg)

Here is my source code

` note.expiry = config.expiry_apns_notification 
                note.badge = 1
                note.sound = "ping.aiff"
                note.alert = title;
                note.payload = payload;
                note.topic = "com.appname";
                note.mutableContent = 1;`

**Comment by florianreinhart** [comment]
Looks OK to me. What's your issue?

**Comment by sirajabbas** [comment]
I cross checked that.It was the mistake from my IOS department.It is working fine without any issues
