### ISSUE TITLE
May be memory leak when "Not receiving Ping response after 150000 ms"

### ISSUE THREAD

**Issue by tian-yuan** [node-apn/node-apn#585]
When "Not receiving Ping response after 150000 ms" occur, 
stream "error" event will be emitted, but stream do not release any more.
provider.shutdown() do not release stream resource also.

**Comment by funkenstrahlen** [comment]
duplicate of #583

**Comment by hopye** [comment]
Still no fix :/ :(

**Comment by not2007** [comment]
memory leak is fixed?
