### ISSUE TITLE
APNS Sandbox Down

### ISSUE THREAD

**Issue by IsaiahJTurner** [node-apn/node-apn#591]
Just a heads up for all those who can't get APNS working today, there appear to be issues with delivering notifications to the Sandbox. Apologies, since this is not a real issue with the project but I think it'll be helpful to leave this open until Apple resolves the issue.

https://stackoverflow.com/questions/46023341/azure-apple-sandbox-apns-issue
https://forums.developer.apple.com/thread/86282

**Comment by thngdude** [comment]
Thanks, was just wondering why my app isn't receiving notifications.
