### ISSUE TITLE
data:application base64 file error 'tls.connect is not a function'.

### ISSUE THREAD

**Issue by wandarkaf** [node-apn/node-apn#593]
I have my certificates and key permissions storage in base64 string like this (storage in a DB):

`data:application/x-x509-ca-cert;base64,LS0tLS....`

when I send the info and try to make the notification (after buffer the file as a string), the notification is send... but it fails:

`"tls.connect is not a function"`

I buffer the cert and key like this: 
` 
let cert = atob(certPem.split('data:application/x-x509-ca-cert;base64,')[1]);
let key = atob(keyPem.split('data:application/x-x509-ca-cert;base64,')[1]);
cert = Buffer.from(certPem);
key = Buffer.from(keyPem);
`

I try locally, with the same permissions, and it works perfectly. I don't know what to do :(

Any hint why this is happening?

**Comment by florianreinhart** [comment]
What node version are you using?
