### ISSUE TITLE
Passing key directly, rather than through .p8 file

### ISSUE THREAD

**Issue by RobinJayaswal** [node-apn/node-apn#594]
I'd like to use this with a server deployed on heroku. The easiest way to provide my private key would be to specify it as an env variable on heroku, and passing that directly:

```
var options = {
  token: {
    key: process.env.TOKEN,
    keyId: 'key-id',
    teamId: 'team-id'
  },
}
```

Is this possible?

It seems to always try and open the file, throwing me

```
Failed loading token key: ENOENT: no such file or directory, open <my private key>
```

**Comment by oliversalzburg** [comment]
> Is this possible?

Yes. Exactly like that pretty much.

**Comment by RobinJayaswal** [comment]
Ah, I realized my mistake. I had to include `-----BEGIN PRIVATE KEY-----` and `-----END PRIVATE KEY-----` in the string passed, then it recognizes it is not a file but a directly passed key. Thanks!
