### ISSUE TITLE
messageFrom does not appear on notification screen anymore

### ISSUE THREAD

**Issue by ickata** [node-apn/node-apn#604]
Hi,

I used to see the "messageFrom" value from notification payload in the notification ballon. Now I can't. My phone is having iOS 11.1. 

I think they might changed something in APN, as other apps continue to show notifications with title and body as before (I use the "messageFrom" as notification title).

**Comment by oliversalzburg** [comment]
To my knowledge, `messageFrom` is not part of the [specified APNS payload arguments](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW1).

**Comment by ickata** [comment]
This is really, really strange. I was using the example from the README of this project where "messageFrom" is specified and indeed it was used as notification title, until some moment. Very strange.

**Comment by oliversalzburg** [comment]
I was searching for it, because we are not using an argument by that name and I was curious. I really only found a reference to the term in this project. If you find out anything, I'd love to know about it :)
