### ISSUE TITLE
Update readme to point at native http2 repo if node version is 8.8.1+

### ISSUE THREAD

**Issue by jpike88** [node-apn/node-apn#605]
Those getting a memory leak warning can avoid it altogether by going here:

https://github.com/andreialecu/node-apn-http2

Those with 8.8.1+ should be directed to try that first I think.

**Comment by florianreinhart** [comment]
We have a branch that uses the native HTTP/2 client, see https://github.com/node-apn/node-apn/tree/native-http2 and #610.
