### ISSUE TITLE
apn version 3.0.0-alpha1: ExperimentalWarning: The http2 module is an experimental API.

### ISSUE THREAD

**Issue by stevenelson74708** [node-apn/node-apn#611]
Node version: 8.9.2

When apn version 3.0.0-alpha1 is installed:

`const apn = require("apn");`

causes the following warning on application startup:

`ExperimentalWarning: The http2 module is an experimental API.`

However, when apn version 2.1.5 is installed:

`const apn = require("apn");`

does not exhibit the warning in the same environment with everything unchanged with the sole exception of the apn version.

Therefore, this warning appears to be an issue with apn version 3.0.0-alpha1.

**Comment by florianreinhart** [comment]
3.0.0 is intentionally labeled as alpha and uses node’s native HTTP/2 client, which is still experimental.
