### ISSUE TITLE
Module HTTP2 missing?

### ISSUE THREAD

**Issue by umutawakil** [node-apn/node-apn#613]
Installed via npm then when running my app I get the following:

Error: Cannot find module 'http2'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app-location/webapp/node_modules/apn/index.js:15:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)

Adding http2 via npm fixes this error then other issues emerge but I imagine I shouldn't have to install the modules sub-dependencies one by one or maybe I'm wrong.

**Comment by roysG** [comment]
Also happened to me.
I also tried to install this package and the i get error:


TypeError: Cannot match against 'undefined' or 'null'.
    at module.exports (/Users/xxx/www/folder/public_html/server/node_modules/apn/lib/client.js:18:12)
...

**Comment by florianreinhart** [comment]
You need to be running the latest node v8 to use node-apn 3.0.0 or a later, which includes native HTTP/2 support. On earlier version you can still use node-apn 2.x.

Next time please include information about your environment (node version, node-apn version, OS etc.) in your issue descriptions.

**Comment by roysG** [comment]
Yes i already did it, thanks anyway.
Ok.

**Comment by Mandark-iprogrammer** [comment]
hello 
my node version is v8.1.3
my npm version is 6.1.0

again i hava facing same problem

**Comment by florianreinhart** [comment]
@Mandark-iprogrammer Please update you node version to 8.11.3 and try again.

**Comment by ollie1995** [comment]
Hi @florianreinhart, 

I also have an issue with apn. 
I'm running Node 8.11.3, any ideas?

0|parse-se | TypeError: Cannot match against 'undefined' or 'null'.
0|parse-se |     at module.exports (/xxxxxx/node_modules/parse-server/node_modules/apn/lib/client.js:18:12)
0|parse-se |     at Object.<anonymous> (/xxxxxx/node_modules/parse-server/node_modules/apn/index.js:17:39)
0|parse-se |     at Module._compile (module.js:570:32)
0|parse-se |     at Object.Module._extensions..js (module.js:579:10)
0|parse-se |     at Module.load (module.js:487:32)
0|parse-se |     at tryModuleLoad (module.js:446:12)
0|parse-se |     at Function.Module._load (module.js:438:3)
0|parse-se |     at Module.require (module.js:497:17)
0|parse-se |     at require (internal/module.js:20:19)
0|parse-se |     at Object.<anonymous> (/xxxxxx/node_modules/parse-server/node_modules/@parse/push-adapter/lib/APNS.js:12:12)

**Comment by ollie1995** [comment]
@florianreinhart,

Never mind, needed to run pm2 update. It looks like PM2 was still using an old Node version despite running nvm install 8.11.3.
