### ISSUE TITLE
Error Code ENOTFOUND 

### ISSUE THREAD

**Issue by dalwadi2** [node-apn/node-apn#614]
Hello, I am using **Firebase functions** to send notification using **APN**.
once we have only one server, In that the functionality is working fine, but we added new Production server and I copied all the codes and files to new folder and deploy it to firebase, and I got this error.

`Result->  production false Call from : Harsh Dalwadi ||  Session Name : Test || {"sent":[],"failed":[{"device":"c425b9aa961e98636c993b837fbcc52eff486ceed737c8a1d1effe23f2eef2b9","error":{"jse_shortmsg":"endpoint error","jse_cause":{"code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"api.development.push.apple.com","host":"api.development.push.apple.com","port":443},"jse_info":{},"message":"endpoint error: getaddrinfo ENOTFOUND api.development.push.apple.com api.development.push.apple.com:443"}}]}`

Can Anyone suggest me what this error is and how can I solve this?
If anyone wants to see the code, I can send.
Really need a help ASAP.
thanks in Advance.

**Comment by florianreinhart** [comment]
This looks like a DNS issue on your server.

Also, you are using the sandbox/development environment of APNs. I am not sure if this is intentional.

**Comment by dalwadi2** [comment]
@florianreinhart I mentioned that I'm using Firebase cloud function.
thanks

**Comment by florianreinhart** [comment]
I got that, but I have no idea how Firebase cloud functions work.

If you lookup ENOTFOUND it should be obvious that node is unable to resolve the domain. This a DNS error not an issue with node-apn.

**Comment by dpark1985** [comment]
same here,

I can send notification from my own server, but not in firebase cloud functions, it gives me an error.
I guess it's the problem with firebase cloud functions

**Comment by dalwadi2** [comment]
@florianreinhart close without the solution ?

**Comment by florianreinhart** [comment]
@dalwadi2 This is not an issue with node-apn. I don't have the time or money to investigate your Firebase environment.

**Comment by sumit10** [comment]
@dalwadi2  This issue occurs due to there are quotas for DNS lookup is google firebase per 100 sec if you have not added your billing info then I had the similar problem and this error I have found in my dashboard "Error: quota exceeded (DNS resolutions : per 100 seconds); to increase quotas, enable billing in your project" just update your billing info in firebase then it will work
