### ISSUE TITLE
VoIP push support

### ISSUE THREAD

**Issue by kmyllyvi** [node-apn/node-apn#618]
Hi.
I'm wondering if this service can be used also to send VoIP push? To my understanding the difference is just type of certificate from Apple (VoIP) and device token.

I've used this for normal APNS push using the generated .p8 certificate, I'm not sure if I can get a VoIP certificate as .p8 tho. Only seen .p12/.pem and those didn't work.

Anyone has any insight on VoIP push?

**Comment by ianlin** [comment]
If you're using token-based and you're good to use it for both normal and VoIP push. The only difference is the notification topic should have `.voip` suffix as described [here][1].

[1]: https://github.com/node-apn/node-apn/issues/464#issuecomment-265557773

**Comment by kmyllyvi** [comment]
Okay. Thanks, I was looking for certificate based solution for now and found another provider making it easy to use .p12 VoIP cert directly. So I'm good. thanks anyhow!

**Comment by pewh** [comment]
Hello, I'm looking for VoiP push support too. But unfortunately I can't make it work. I'm already following `.voip` suffix but still didn't work. May I know what another provider do you use, @kmyllyvi ? Thank you

**Comment by pushkar803** [comment]
please tell @kmyllyvi  which is other provider u found
?

**Comment by kmyllyvi** [comment]
Hi sorry for not following up @pewh - Maybe it's still current for some ppl: been using apnagent https://www.npmjs.com/package/apnagent for VoIP push using .p12 cert. Hope that works for you as well @pushkar803

**Comment by pushkar803** [comment]
thank you man
