### ISSUE TITLE
is it possible to send push to multiple devices with multiple (different) badge values?

### ISSUE THREAD

**Issue by alionthego** [node-apn/node-apn#623]
I am sending notifications to multiple devices passing an array of device tokens as shown below:

```
apnProvider.send(notification, [deviceTokenArray1, deviceToken2, deviceToken3]).then((response) => {
    // do stuff
}
```

If I want to send notifications to multiple devices with each one having a different badge value, can that be done at once also passing an array of deviceTokens and an array of badge counts or do I need to loop through and send each notification separately?  At the moment I am doing the loop shown below.

```
var apnProvider = new apn.Provider(options);

for (var j = 0; j < users.length; j++) {
    
    var notification = new apn.Notification();
                
    notification.alert = "alertMessage";
    notification.badge = users[j].badge;
    notification.topic = "com.example.example";  
    
    apnProvider.send(notification, [users[j].deviceToken]).then((response) => {
        // do stuff
    }           
}

```

Assuming the only way to do this is by looping, will it take quite long for a few dozen devices?

**Comment by florianreinhart** [comment]
You will have to loop through them.

There won't be any performance impact. In the end node-apn has to send a separate notification for every device token.
