### ISSUE TITLE
token.key getting logic cut out relative path

### ISSUE THREAD

**Issue by Jollarvia** [node-apn/node-apn#625]
I notice that when I enter in my key as "../../mykey.p8" apn chops off the relative part and takes only the file name and I don't seem to be able to place mykey.p8 anywhere except the place I required apn at.  I expected it to search "path_outside_my_app/mykey.p8" but it searches "path_outside_my_app/my_app/my_require_location/mykey.p8". Maybe I'm doing it wrong, it is my first day with it. Was there a design decision around this or could we change this to search anywhere the developer pleases? Personally, I'd like to keep the key centralized - and out of reach of web server - and away from other devs - and out of git - and I don't feel like git ignoring.

**Comment by florianreinhart** [comment]
I think relative paths should work. node-apn internally uses node's fs package to load a file: `fs.readFileSync(value)` in [resolve.js](https://github.com/node-apn/node-apn/blob/09b459cfff0bbb670cdd8c8e1409ef600cbd7c64/lib/credentials/resolve.js#L16).

You can also load the key manually and pass a buffer when creating a new `Provider` instance, see https://github.com/node-apn/node-apn/blob/master/doc/provider.markdown
