### ISSUE TITLE
TopicDisallowed when trying to push notification

### ISSUE THREAD

**Issue by eduardmo** [node-apn/node-apn#635]
Hello,

I am trying to create a notification and push it to my device. I'm using a WebRTC implementation hosted on localhost to make the request but it fails saying that TopicDisallowed. The certificates are alright, I'm using the production ones, the key.p8 is the correct one, the bundleID name used for the topic is the one showed on developer page. 
Here you can see the token and the notification:
[  var apnProvider = new apn.Provider({
  token: {
    key: "cert/key.p8",
    keyId: "66PWSYBDA2",
    teamId: "48SRYYH66F"
  },
  production: true
  });

  if (deviceToken) {
        if (platform === 'ios') {
          let note = new apn.Notification()
          note.alert = 'Hello World'
          note = Object.assign(note, {
            // Expires 1 hour from now.
            expiry: Math.floor(Date.now() / 1000) + 3600,
            badge: 3,
            payload: payloadBody,
            topic: "org.hanze.TranslatorApp"
          })

          apnProvider.send(note, deviceToken).then((result) => {
            console.log('APNPROVIDER RESULT', `PLATFORM: ${platform}, RESULT:${JSON.stringify(result)}`)
          })](url)

**Comment by arapocket** [comment]
Did you figure out what was wrong?

**Comment by eduardmo** [comment]
Yes, I did. If I recall correct l I had to add .voip at the final of the topic because my notification was in fact a call implementation. I hope it helps.

**Comment by arapocket** [comment]
@eduardmo Thank you. It turns out I just had the wrong name for my note topic.
