### ISSUE TITLE
GCM deprecated (EOL 2019.05.29 !)

### ISSUE THREAD

**Issue by rdewolff** [node-apn/node-apn#655]
Hello

As GCM is deprecated [1], are you planning on integrating Firebase Cloud Messaging (FCM) in the lib ?

Do we have other alternatives to keep using this lib with Android ?

[1] : https://developers.google.com/cloud-messaging/

**Comment by florianreinhart** [comment]
node-apn does not support GCM or FCM. It's just for APNs.

**Comment by rdewolff** [comment]
Oh sorry, intended to commit this issue in https://github.com/appfeel/node-pushnotifications. 

And this is the case, will be supported : https://github.com/appfeel/node-pushnotifications/issues/96
