### ISSUE TITLE
Only VoIP topic works

### ISSUE THREAD

**Issue by rostopira** [node-apn/node-apn#658]
I need both, VoIP and regular push notifications
If I send VoIP push using "my.bundle.voip" topic it works just fine
But when I try to send regular notification, it says "TopicDissallowed"
Any advice?
I've tried certificate (pfx: 'apns.p12') and with key (token: { key: 'apns.p8' ....})

**Comment by rostopira** [comment]
Well, I've used voip token for both, that's the issue

**Comment by ThanhNghia944** [comment]
hi @rostopira  you can  help me show code to use VoIP  push ?
