### ISSUE TITLE
How do I redirect a notification click to a URL ?

### ISSUE THREAD

**Issue by bholagabbar** [node-apn/node-apn#662]
I'm looking for a way to embedd a deep-link (or even a URL link) into my push notification. When users click on the notification, they are redirected within the application to a certain page in the application. I have a URL `zy://page/id` that I want to redirect them to and this needs to be embedded in the notification. Does the library provide a way to do this ?

I have only seen the `urlArgs` option in notification docs.

**Comment by WestFlow127** [comment]
I have this same question..

**Comment by FlorianMarcon** [comment]
Hello @bholagabbar,

Did you find a solution ?
