### ISSUE TITLE
[URGENT] Unable to send notifications to iOS 13 devices

### ISSUE THREAD

**Issue by iamromec** [node-apn/node-apn#670]
Hello team,

After the rediculous change by apple, I'm unable to send notifications to Apple devices. As our platform is a chatting platform and for that, we highly required this to be fixed as soon as possible.

Previously Apple returned device token in this format: 64810a2ebfcc4c15f42ab5c8870c9e2589a998fff55ccfeef50dda99aa5e1d65

But after iOS 13, we're receiving tokens like this:
{length=32,bytes=0x8a58d88cc4c3d4da2504046df790becf...3f8412c657ce0bd0}

We really need urgent help...how can we decode it or send notifications with this format.

**Comment by wiggisser** [comment]
This is not an issue of this library but of your iOS native app. See for instance https://stackoverflow.com/questions/57839723/does-ios-13-has-new-way-of-getting-device-notification-token for the correct way of retrieving the token

**Comment by iamromec** [comment]
I'm closing the issue as I've written the solution here: https://github.com/node-apn/node-apn/issues/666#issuecomment-551842757
